/**
 * abc-strings.js — strings of the Flip & Learn ABC landing page (/abc/, /<loc>/abc/).
 *
 * Same pattern as the T table in index.html and P/PW in privacy-strings.js: one object
 * per locale, keyed by the data-i18n / data-i18n-aria keys used in abc/index.html.
 * build-locales.js merges A[code] over T[code] (which supplies the cookie.* and nav.*
 * keys of the shared chrome) and emits a page for every locale in ABC_LOCALES.
 *
 * Rules for every locale (see build-locales.md):
 *   - "Flip & Learn", "Flip & Learn ABC", "ABC" and "Mo" are never translated.
 *   - The Words app is always called by its Google Play title in the page's language,
 *     verbatim: flipandlearn_flutter android/fastlane/metadata/android/<locale>/title.txt
 *     (en "Flip & Learn: Word Card Game", hu "Flip & Learn: Szókártyajáték",
 *     ro "Flip & Learn: Joc de cuvinte"). Where Play has no localized title, use the
 *     English title. Never inflect, shorten or translate the name; build the sentence
 *     around it. (Rule set by Laci, 2026-10-04.)
 *   - Game names are the app's own on-screen names (ABC repo, lib/l10n/app_<loc>.arb).
 *   - The app teaches the alphabet of English, German, Spanish, French, Romanian,
 *     Hungarian or Italian — never the alphabet of the page's own language unless it
 *     is one of those seven.
 *   - No age claim. Never "completely free". Never the word "memory" or a cognate.
 */
'use strict';

const A = {
en: {
"abc.meta.title": "Flip & Learn ABC — Learn the alphabet by playing",
"abc.meta.ogalt": "The Flip & Learn ABC app icon next to the name Flip & Learn ABC",
"abc.meta.desc": "Nine letter games for small hands: matching, tracing, popping balloons and feeding Mo. Letters and words are spoken in seven languages. Free — no ads, no in-app purchases.",

"abc.nav.aria": "Page sections",
"abc.nav.games": "Games",
"abc.nav.languages": "Languages",
"abc.nav.parents": "For parents",
"abc.nav.words": "Flip & Learn: Word Card Game",
"abc.lang.aria": "Change page language",

"abc.hero.h1": "Learn the alphabet by playing.",
"abc.hero.sub": "Nine little letter games for small hands — matching, tracing, popping balloons and feeding Mo the monster. Letters and words are spoken aloud in English, German, Spanish, French, Romanian, Hungarian and Italian.",
"abc.hero.soon": "Coming soon to the App Store and Google Play",
"abc.badge.apple": "Download Flip & Learn ABC on the App Store",
"abc.badge.play": "Get Flip & Learn ABC on Google Play",
"abc.chip.free": "Free",
"abc.chip.ads": "No ads",
"abc.chip.iap": "No in-app purchases",
"abc.chip.offline": "Works offline",
"abc.chip.data": "No data collected",

"abc.shot.aria": "Screenshots of the app",
"abc.shot.p1.alt": "Flip & Learn ABC Home screen, page 1: Letter Match, Case Match, Word Match, Letter Trace",
"abc.shot.p2.alt": "Flip & Learn ABC Home screen, page 2: Balloon Pop, Hungry Mo, Connect the Dots, Letter Fishing, Sorting Baskets",
"abc.shot.prev": "Previous screen",
"abc.shot.next": "Next screen",
"abc.shot.dot1": "Show page 1",
"abc.shot.dot2": "Show page 2",

"abc.langs.eyebrow": "Letters of the world",
"abc.langs.h2": "Seven alphabets, special letters included.",
"abc.langs.p": "Pick one of seven languages. Its special letters, like Ș, ß, Ñ or Gy, are letters of their own in the games. When no word starts with a letter, Word Match uses a word that contains it.",
"abc.lang.n26": "26 letters",
"abc.lang.n27": "27 letters",
"abc.lang.n30": "30 letters",
"abc.lang.n31": "31 letters",
"abc.lang.n44": "44 letters",
"abc.menus.h3": "Menus in 18 languages",
"abc.menus.p": "English, German, Spanish, French, Italian, Portuguese, Romanian, Hungarian, Turkish, Slovenian, Dutch, Bulgarian, Ukrainian, Russian, Polish, Czech, Slovak and Croatian. With any other device language, the menus are in English.",

"abc.games.eyebrow": "Nine games, one alphabet",
"abc.games.h2": "A new way to meet the letters every day.",
"abc.game.lm.name": "Letter Match",
"abc.game.lm.desc": "Flip the cards and find two of the same letter. Its name is spoken on every match.",
"abc.game.cm.name": "Case Match",
"abc.game.cm.desc": "Pair every capital letter with its small partner.",
"abc.game.wm.name": "Word Match",
"abc.game.wm.word": "dolphin",
"abc.game.wm.desc": "Match a letter to a picture word that starts with it — animals, fruits and more.",
"abc.game.lt.name": "Letter Trace",
"abc.game.lt.desc": "Trace each letter with a finger, stroke by stroke. A moving dot shows the way first.",
"abc.game.bp.name": "Balloon Pop",
"abc.game.bp.desc": "Pop the balloons that carry the letters of the picture word. A new word every game.",
"abc.game.mo.name": "Hungry Mo",
"abc.game.mo.desc": "Mo is hungry. Feed him the pictures that start with his letter — and wait for the burp.",
"abc.game.cd.name": "Connect the Dots",
"abc.game.cd.desc": "Draw from letter to letter in alphabet order. At the last dot the picture fills with color and comes alive.",
"abc.game.lf.name": "Letter Fishing",
"abc.game.lf.desc": "Listen for the letter, then tap the fish that carries it. Five catches make a game.",
"abc.game.sb.name": "Sorting Baskets",
"abc.game.sb.desc": "Drag each picture into the basket of its first letter. Nothing is timed.",

"abc.parents.eyebrow": "For parents",
"abc.parents.h2": "Made by a parent. Safe by design.",
"abc.parents.p1": "Flip & Learn began as an app for my own son. I build every Flip & Learn app myself in Regensburg, Germany, with the same care.",
"abc.parents.p2": "Flip & Learn ABC has nothing to buy, nothing to sign up for, and it collects no data.",
"abc.parents.privacy": "Read the ABC privacy policy",
"abc.safe.ads.t": "No ads",
"abc.safe.ads.d": "Nothing pulls your child out of the game.",
"abc.safe.iap.t": "No in-app purchases",
"abc.safe.iap.d": "All nine games are included.",
"abc.safe.data.t": "No data collected",
"abc.safe.data.d": "The app saves only a few settings, and only on the device.",
"abc.safe.offline.t": "Works offline",
"abc.safe.offline.d": "No internet connection is needed to play.",
"abc.safe.gate.t": "Parents' area",
"abc.safe.gate.d": "Settings and links sit behind a parental gate.",
"abc.safe.hints.t": "Gentle hints",
"abc.safe.hints.d": "A lightbulb helps in the three matching games. Switch it off in the parents' area.",

"abc.words.eyebrow": "Next step: words",
"abc.words.h2": "Letters done? Time for words.",
"abc.words.p": "Flip & Learn: Word Card Game comes from the same family: 21+ categories, 9 languages, and every word spoken out loud.",
"abc.words.badge": "Teacher Approved on Google Play",
"abc.words.card": "dog",
"abc.words.cta": "Discover Flip & Learn: Word Card Game",

"abc.print.h2": "Free tracing worksheets",
"abc.print.p": "Print a coloring page and trace the word with a pencil. Then practice letters in Letter Trace.",
"abc.print.cta": "Get the printables",

"abc.foot.aria": "Footer",
"abc.foot.motto": "Education belongs to every child.",
"abc.foot.words": "Flip & Learn: Word Card Game",
"abc.foot.privacy": "ABC privacy",
},

// Hungarian. Game names, button labels and the phone-mockup texts are taken verbatim
// from the ABC app (lib/l10n/app_hu.arb). Informal address (tegezés), as on /hu/.
hu: {
"abc.meta.title": "Flip & Learn ABC — Tanuld meg az ábécét játszva",
"abc.meta.ogalt": "A Flip & Learn ABC alkalmazás ikonja a Flip & Learn ABC név mellett",
"abc.meta.desc": "Kilenc betűjáték kis kezeknek: párosítás, betűrajzolás, lufipukkasztás és Mo etetése. A betűk és a szavak hét nyelven hangzanak el. Ingyenes — reklámok és alkalmazáson belüli vásárlás nélkül.",

"abc.nav.aria": "Az oldal részei",
"abc.nav.games": "Játékok",
"abc.nav.languages": "Nyelvek",
"abc.nav.parents": "Szülőknek",
"abc.nav.words": "Flip & Learn: Szókártyajáték",
"abc.lang.aria": "Az oldal nyelvének váltása",

"abc.hero.h1": "Tanuld meg az ábécét játszva.",
"abc.hero.sub": "Kilenc kis betűjáték apró kezeknek — párosítás, betűrajzolás, lufipukkasztás és Mo, a szörny etetése. A betűk és a szavak hangosan elhangzanak angolul, németül, spanyolul, franciául, románul, magyarul és olaszul.",
"abc.hero.soon": "Hamarosan az App Store-ban és a Google Playen",
"abc.badge.apple": "A Flip & Learn ABC letöltése az App Store-ból",
"abc.badge.play": "A Flip & Learn ABC letöltése a Google Playről",
"abc.chip.free": "Ingyenes",
"abc.chip.ads": "Nincs reklám",
"abc.chip.iap": "Nincs alkalmazáson belüli vásárlás",
"abc.chip.offline": "Offline működik",
"abc.chip.data": "Nincs adatgyűjtés",

"abc.shot.aria": "Képernyőképek az alkalmazásból",
"abc.shot.p1.alt": "A Flip & Learn ABC kezdőképernyője, 1. oldal: Betűk, Nagy és kis betű, Szavak, Betűk rajzolása",
"abc.shot.p2.alt": "A Flip & Learn ABC kezdőképernyője, 2. oldal: Lufipukkasztás, Éhes Mo, Kösd össze a pontokat, Betűhorgászat, Válogató kosarak",
"abc.shot.prev": "Előző képernyő",
"abc.shot.next": "Következő képernyő",
"abc.shot.dot1": "1. oldal megjelenítése",
"abc.shot.dot2": "2. oldal megjelenítése",

"abc.langs.eyebrow": "A világ betűi",
"abc.langs.h2": "Hét ábécé, a különleges betűkkel együtt.",
"abc.langs.p": "Válassz a hét nyelv közül. A különleges betűk — például Ș, ß, Ñ vagy Gy — a játékokban önálló betűk. Ha egy betűvel nem kezdődik szó, a Szavak játék olyan szót mutat, amelyben a betű szerepel.",
"abc.lang.n26": "26 betű",
"abc.lang.n27": "27 betű",
"abc.lang.n30": "30 betű",
"abc.lang.n31": "31 betű",
"abc.lang.n44": "44 betű",
"abc.menus.h3": "Menük 18 nyelven",
"abc.menus.p": "Angol, német, spanyol, francia, olasz, portugál, román, magyar, török, szlovén, holland, bolgár, ukrán, orosz, lengyel, cseh, szlovák és horvát. Ha a készülék nyelve más, a menük angolul jelennek meg.",

"abc.games.eyebrow": "Kilenc játék, egy ábécé",
"abc.games.h2": "Minden nap új találkozás a betűkkel.",
"abc.game.lm.name": "Betűk",
"abc.game.lm.desc": "Fordítsd fel a kártyákat, és keresd meg a két azonos betűt. Minden találatnál elhangzik a betű neve.",
"abc.game.cm.name": "Nagy és kis betű",
"abc.game.cm.desc": "Párosíts minden nagybetűt a kisbetűs párjával.",
"abc.game.wm.name": "Szavak",
"abc.game.wm.word": "delfin",
"abc.game.wm.desc": "Párosíts egy betűt egy képes szóval, amely azzal a betűvel kezdődik — állatok, gyümölcsök és még sok más.",
"abc.game.lt.name": "Betűk rajzolása",
"abc.game.lt.desc": "Rajzold meg a betűket az ujjaddal, vonásról vonásra. Előbb egy mozgó pont mutatja az utat.",
"abc.game.bp.name": "Lufipukkasztás",
"abc.game.bp.desc": "Pukkaszd ki azokat a lufikat, amelyeken a képhez tartozó szó betűi vannak. Minden játékban új szó.",
"abc.game.mo.name": "Éhes Mo",
"abc.game.mo.desc": "Mo éhes. Etesd meg azokkal a képekkel, amelyek az ő betűjével kezdődnek — és várd meg a böfögést.",
"abc.game.cd.name": "Kösd össze a pontokat",
"abc.game.cd.desc": "Húzz vonalat betűtől betűig, ábécésorrendben. Az utolsó pontnál a kép kiszíneződik és megelevenedik.",
"abc.game.lf.name": "Betűhorgászat",
"abc.game.lf.desc": "Hallgasd meg a betűt, majd koppints arra a halra, amelyiken rajta van. Öt fogás egy játék.",
"abc.game.sb.name": "Válogató kosarak",
"abc.game.sb.desc": "Húzd minden képet a kezdőbetűjének kosarába. Nincs időmérés.",

"abc.parents.eyebrow": "Szülőknek",
"abc.parents.h2": "Egy szülő készítette. Biztonságosra tervezve.",
"abc.parents.p1": "A Flip & Learn a saját fiamnak készült alkalmazásként indult. Minden Flip & Learn alkalmazást magam készítek a németországi Regensburgban, ugyanazzal a gondossággal.",
"abc.parents.p2": "A Flip & Learn ABC-ben nincs mit megvenni, nem kell regisztrálni, és nem gyűjt adatokat.",
"abc.parents.privacy": "Olvasd el az ABC adatvédelmi irányelveit (angol nyelven)",
"abc.safe.ads.t": "Nincs reklám",
"abc.safe.ads.d": "Semmi sem zökkenti ki a gyermekedet a játékból.",
"abc.safe.iap.t": "Nincs alkalmazáson belüli vásárlás",
"abc.safe.iap.d": "Mind a kilenc játék benne van.",
"abc.safe.data.t": "Nincs adatgyűjtés",
"abc.safe.data.d": "Az alkalmazás csak néhány beállítást ment el, és csak a készüléken.",
"abc.safe.offline.t": "Offline működik",
"abc.safe.offline.d": "A játékhoz nem kell internetkapcsolat.",
"abc.safe.gate.t": "Szülői rész",
"abc.safe.gate.d": "A beállítások és a hivatkozások szülői ellenőrzés mögött vannak.",
"abc.safe.hints.t": "Segítség, ha kell",
"abc.safe.hints.d": "A három párosító játékban egy villanykörte segít. A Szülőknek részben kikapcsolható.",

"abc.words.eyebrow": "Következő lépés: szavak",
"abc.words.h2": "Megvannak a betűk? Jöhetnek a szavak.",
"abc.words.p": "A Flip & Learn: Szókártyajáték ugyanebből a családból való: 21+ kategória, 9 nyelv, és minden szót hangosan kimond.",
"abc.words.badge": "Tanárok által jóváhagyva a Google Playen",
"abc.words.card": "kutya",
"abc.words.cta": "Irány a Flip & Learn: Szókártyajáték",

"abc.print.h2": "Ingyenes betűrajzoló feladatlapok",
"abc.print.p": "Nyomtass ki egy színezőt, és rajzold át a szót ceruzával. Utána gyakorold a betűket a Betűk rajzolása játékban.",
"abc.print.cta": "Nyomtatható feladatlapok",

"abc.foot.aria": "Lábléc",
"abc.foot.motto": "Az oktatás minden gyermeket megillet.",
"abc.foot.words": "Flip & Learn: Szókártyajáték",
"abc.foot.privacy": "ABC adatvédelem (angolul)",
},

// Romanian. Game names, button labels and the phone-mockup texts are taken verbatim
// from the ABC app (lib/l10n/app_ro.arb). Informal address (tu), as on /ro/.
// Comma-below Ș ș Ț ț only — never the cedilla forms.
ro: {
"abc.meta.title": "Flip & Learn ABC — Învață alfabetul prin joacă",
"abc.meta.ogalt": "Pictograma aplicației Flip & Learn ABC lângă numele Flip & Learn ABC",
"abc.meta.desc": "Nouă jocuri cu litere pentru mâini mici: potrivire, trasare, spart baloane și hrănirea lui Mo. Literele și cuvintele sunt rostite în șapte limbi. Gratuit — fără reclame, fără achiziții în aplicație.",

"abc.nav.aria": "Secțiunile paginii",
"abc.nav.games": "Jocuri",
"abc.nav.languages": "Limbi",
"abc.nav.parents": "Pentru părinți",
"abc.nav.words": "Flip & Learn: Joc de cuvinte",
"abc.lang.aria": "Schimbă limba paginii",

"abc.hero.h1": "Învață alfabetul prin joacă.",
"abc.hero.sub": "Nouă jocuri cu litere pentru mâini mici — potrivire, trasare, spart baloane și hrănirea lui Mo, monstrul. Literele și cuvintele sunt rostite cu voce tare în engleză, germană, spaniolă, franceză, română, maghiară și italiană.",
"abc.hero.soon": "În curând în App Store și pe Google Play",
"abc.badge.apple": "Descarcă Flip & Learn ABC din App Store",
"abc.badge.play": "Descarcă Flip & Learn ABC de pe Google Play",
"abc.chip.free": "Gratuit",
"abc.chip.ads": "Fără reclame",
"abc.chip.iap": "Fără achiziții în aplicație",
"abc.chip.offline": "Funcționează offline",
"abc.chip.data": "Fără colectare de date",

"abc.shot.aria": "Capturi de ecran din aplicație",
"abc.shot.p1.alt": "Ecranul principal Flip & Learn ABC, pagina 1: Litere, Literă mare și mică, Cuvinte, Trasează literele",
"abc.shot.p2.alt": "Ecranul principal Flip & Learn ABC, pagina 2: Sparge baloanele, Mo cel flămând, Unește punctele, Pescuit de litere, Coșuri de sortat",
"abc.shot.prev": "Ecranul anterior",
"abc.shot.next": "Ecranul următor",
"abc.shot.dot1": "Arată pagina 1",
"abc.shot.dot2": "Arată pagina 2",

"abc.langs.eyebrow": "Literele lumii",
"abc.langs.h2": "Șapte alfabete, cu tot cu literele speciale.",
"abc.langs.p": "Alege una dintre cele șapte limbi. Literele ei speciale, precum Ș, ß, Ñ sau Gy, sunt litere de sine stătătoare în jocuri. Când niciun cuvânt nu începe cu o literă, jocul Cuvinte folosește un cuvânt care o conține.",
"abc.lang.n26": "26 de litere",
"abc.lang.n27": "27 de litere",
"abc.lang.n30": "30 de litere",
"abc.lang.n31": "31 de litere",
"abc.lang.n44": "44 de litere",
"abc.menus.h3": "Meniuri în 18 limbi",
"abc.menus.p": "Engleză, germană, spaniolă, franceză, italiană, portugheză, română, maghiară, turcă, slovenă, neerlandeză, bulgară, ucraineană, rusă, poloneză, cehă, slovacă și croată. Pentru orice altă limbă a dispozitivului, meniurile sunt în engleză.",

"abc.games.eyebrow": "Nouă jocuri, un alfabet",
"abc.games.h2": "În fiecare zi, un nou fel de a întâlni literele.",
"abc.game.lm.name": "Litere",
"abc.game.lm.desc": "Întoarce cărțile și găsește două cu aceeași literă. La fiecare pereche, numele literei este rostit.",
"abc.game.cm.name": "Literă mare și mică",
"abc.game.cm.desc": "Potrivește fiecare literă mare cu perechea ei mică.",
"abc.game.wm.name": "Cuvinte",
"abc.game.wm.word": "delfin",
"abc.game.wm.desc": "Potrivește o literă cu un cuvânt ilustrat care începe cu ea — animale, fructe și multe altele.",
"abc.game.lt.name": "Trasează literele",
"abc.game.lt.desc": "Trasează fiecare literă cu degetul, linie cu linie. Mai întâi, un punct în mișcare arată drumul.",
"abc.game.bp.name": "Sparge baloanele",
"abc.game.bp.desc": "Sparge baloanele care poartă literele cuvântului din imagine. La fiecare joc, un cuvânt nou.",
"abc.game.mo.name": "Mo cel flămând",
"abc.game.mo.desc": "Lui Mo îi este foame. Dă-i imaginile care încep cu litera lui — și așteaptă râgâitul.",
"abc.game.cd.name": "Unește punctele",
"abc.game.cd.desc": "Trasează de la literă la literă, în ordine alfabetică. La ultimul punct, imaginea se umple de culoare și prinde viață.",
"abc.game.lf.name": "Pescuit de litere",
"abc.game.lf.desc": "Ascultă litera, apoi atinge peștele care o poartă. Cinci capturi fac un joc.",
"abc.game.sb.name": "Coșuri de sortat",
"abc.game.sb.desc": "Trage fiecare imagine în coșul primei ei litere. Nimic nu este cronometrat.",

"abc.parents.eyebrow": "Pentru părinți",
"abc.parents.h2": "Creat de un părinte. Sigur prin concepție.",
"abc.parents.p1": "Flip & Learn a început ca o aplicație pentru fiul meu. Fac eu însumi fiecare aplicație Flip & Learn, în Regensburg, Germania, cu aceeași grijă.",
"abc.parents.p2": "În Flip & Learn ABC nu e nimic de cumpărat, nu trebuie creat niciun cont și nu se colectează date.",
"abc.parents.privacy": "Citește politica de confidențialitate ABC (în limba engleză)",
"abc.safe.ads.t": "Fără reclame",
"abc.safe.ads.d": "Nimic nu îți scoate copilul din joc.",
"abc.safe.iap.t": "Fără achiziții în aplicație",
"abc.safe.iap.d": "Toate cele nouă jocuri sunt incluse.",
"abc.safe.data.t": "Fără colectare de date",
"abc.safe.data.d": "Aplicația salvează doar câteva setări, și numai pe dispozitiv.",
"abc.safe.offline.t": "Funcționează offline",
"abc.safe.offline.d": "Nu este nevoie de internet pentru a juca.",
"abc.safe.gate.t": "Zona pentru părinți",
"abc.safe.gate.d": "Setările și linkurile se află în spatele controlului parental.",
"abc.safe.hints.t": "Indicii blânde",
"abc.safe.hints.d": "Un bec ajută în cele trei jocuri de potrivire. Se poate dezactiva în zona Pentru părinți.",

"abc.words.eyebrow": "Pasul următor: cuvinte",
"abc.words.h2": "Gata cu literele? E timpul pentru cuvinte.",
"abc.words.p": "Flip & Learn: Joc de cuvinte vine din aceeași familie: 21+ categorii, 9 limbi și fiecare cuvânt rostit cu voce tare.",
"abc.words.badge": "Aprobat de profesori pe Google Play",
"abc.words.card": "câine",
"abc.words.cta": "Descoperă Flip & Learn: Joc de cuvinte",

"abc.print.h2": "Fișe de colorat gratuite cu exerciții de scriere",
"abc.print.p": "Printează o fișă de colorat și trasează cuvântul cu creionul. Apoi exersează literele în jocul Trasează literele.",
"abc.print.cta": "Vezi fișele de colorat",

"abc.foot.aria": "Subsol",
"abc.foot.motto": "Educația aparține fiecărui copil.",
"abc.foot.words": "Flip & Learn: Joc de cuvinte",
"abc.foot.privacy": "Confidențialitate ABC (în engleză)",
},

// German (AI draft). Informal "du", as on /de/. ABC game language.
// Game names and "For parents" verbatim from the ABC app (lib/l10n/app_de.arb);
// Words app name verbatim from Google Play (de-DE/title.txt).
de: {
"abc.meta.title": "Flip & Learn ABC — Das Alphabet spielend lernen",
"abc.meta.ogalt": "Das App-Icon von Flip & Learn ABC neben dem Namen Flip & Learn ABC",
"abc.meta.desc": "Neun Buchstabenspiele für kleine Hände: zuordnen, nachspuren, Ballons platzen lassen und Mo füttern. Buchstaben und Wörter werden in sieben Sprachen vorgesprochen. Kostenlos — keine Werbung, keine In-App-Käufe.",
"abc.nav.aria": "Seitenbereiche",
"abc.nav.games": "Spiele",
"abc.nav.languages": "Sprachen",
"abc.nav.parents": "Für Eltern",
"abc.nav.words": "Flip & Learn: Wortkartenspiel",
"abc.lang.aria": "Seitensprache ändern",
"abc.hero.h1": "Das Alphabet spielend lernen.",
"abc.hero.sub": "Neun kleine Buchstabenspiele für kleine Hände — zuordnen, nachspuren, Ballons platzen lassen und Mo, das Monster, füttern. Buchstaben und Wörter werden laut vorgesprochen: auf Deutsch, Englisch, Spanisch, Französisch, Rumänisch, Ungarisch und Italienisch.",
"abc.hero.soon": "Bald im App Store und bei Google Play",
"abc.badge.apple": "Flip & Learn ABC im App Store laden",
"abc.badge.play": "Flip & Learn ABC bei Google Play laden",
"abc.chip.free": "Kostenlos",
"abc.chip.ads": "Keine Werbung",
"abc.chip.iap": "Keine In-App-Käufe",
"abc.chip.offline": "Funktioniert offline",
"abc.chip.data": "Keine Datenerfassung",
"abc.shot.aria": "Screenshots der App",
"abc.shot.p1.alt": "Startbildschirm von Flip & Learn ABC, Seite 1: Buchstaben, Groß & klein, Wörter, Buchstaben nachspuren",
"abc.shot.p2.alt": "Startbildschirm von Flip & Learn ABC, Seite 2: Ballons platzen, Hungriger Mo, Punkte verbinden, Buchstaben angeln, Sortierkörbe",
"abc.shot.prev": "Vorheriger Bildschirm",
"abc.shot.next": "Nächster Bildschirm",
"abc.shot.dot1": "Seite 1 anzeigen",
"abc.shot.dot2": "Seite 2 anzeigen",
"abc.langs.eyebrow": "Buchstaben der Welt",
"abc.langs.h2": "Sieben Alphabete, Sonderbuchstaben inklusive.",
"abc.langs.p": "Wähle eine von sieben Sprachen. Ihre besonderen Buchstaben wie Ș, ß, Ñ oder Gy sind in den Spielen eigene Buchstaben. Beginnt kein Wort mit einem Buchstaben, nimmt das Spiel Wörter ein Wort, das ihn enthält.",
"abc.lang.n26": "26 Buchstaben",
"abc.lang.n27": "27 Buchstaben",
"abc.lang.n30": "30 Buchstaben",
"abc.lang.n31": "31 Buchstaben",
"abc.lang.n44": "44 Buchstaben",
"abc.menus.h3": "Menüs in 18 Sprachen",
"abc.menus.p": "Englisch, Deutsch, Spanisch, Französisch, Italienisch, Portugiesisch, Rumänisch, Ungarisch, Türkisch, Slowenisch, Niederländisch, Bulgarisch, Ukrainisch, Russisch, Polnisch, Tschechisch, Slowakisch und Kroatisch. Bei jeder anderen Gerätesprache erscheinen die Menüs auf Englisch.",
"abc.games.eyebrow": "Neun Spiele, ein Alphabet",
"abc.games.h2": "Jeden Tag den Buchstaben neu begegnen.",
"abc.game.lm.name": "Buchstaben",
"abc.game.lm.desc": "Dreh die Karten um und finde zweimal denselben Buchstaben. Bei jedem Treffer wird sein Name gesprochen.",
"abc.game.cm.name": "Groß & klein",
"abc.game.cm.desc": "Finde zu jedem Großbuchstaben seinen kleinen Partner.",
"abc.game.wm.name": "Wörter",
"abc.game.wm.word": "Delfin",
"abc.game.wm.desc": "Ordne einem Buchstaben ein Bildwort zu, das mit ihm beginnt — Tiere, Obst und mehr.",
"abc.game.lt.name": "Buchstaben nachspuren",
"abc.game.lt.desc": "Spure jeden Buchstaben mit dem Finger nach, Strich für Strich. Ein wandernder Punkt zeigt vorher den Weg.",
"abc.game.bp.name": "Ballons platzen",
"abc.game.bp.desc": "Lass die Ballons platzen, die die Buchstaben des Bildworts tragen. In jedem Spiel ein neues Wort.",
"abc.game.mo.name": "Hungriger Mo",
"abc.game.mo.desc": "Mo hat Hunger. Füttere ihn mit den Bildern, die mit seinem Buchstaben beginnen — und warte auf den Rülpser.",
"abc.game.cd.name": "Punkte verbinden",
"abc.game.cd.desc": "Zeichne von Buchstabe zu Buchstabe, in der Reihenfolge des Alphabets. Beim letzten Punkt füllt sich das Bild mit Farbe und wird lebendig.",
"abc.game.lf.name": "Buchstaben angeln",
"abc.game.lf.desc": "Hör dir den Buchstaben an und tippe dann den Fisch an, der ihn trägt. Fünf Fänge sind ein Spiel.",
"abc.game.sb.name": "Sortierkörbe",
"abc.game.sb.desc": "Zieh jedes Bild in den Korb seines Anfangsbuchstabens. Ganz ohne Zeitdruck.",
"abc.parents.eyebrow": "Für Eltern",
"abc.parents.h2": "Von einem Vater gemacht. Von Grund auf sicher.",
"abc.parents.p1": "Flip & Learn begann als App für meinen eigenen Sohn. Jede Flip & Learn App entwickle ich selbst in Regensburg, Deutschland, mit derselben Sorgfalt.",
"abc.parents.p2": "In Flip & Learn ABC gibt es nichts zu kaufen, keine Anmeldung, und die App erfasst keine Daten.",
"abc.parents.privacy": "Datenschutzerklärung von ABC lesen (auf Englisch)",
"abc.safe.ads.t": "Keine Werbung",
"abc.safe.ads.d": "Nichts reißt dein Kind aus dem Spiel.",
"abc.safe.iap.t": "Keine In-App-Käufe",
"abc.safe.iap.d": "Alle neun Spiele sind enthalten.",
"abc.safe.data.t": "Keine Datenerfassung",
"abc.safe.data.d": "Die App speichert nur ein paar Einstellungen, und nur auf dem Gerät.",
"abc.safe.offline.t": "Funktioniert offline",
"abc.safe.offline.d": "Zum Spielen ist keine Internetverbindung nötig.",
"abc.safe.gate.t": "Elternbereich",
"abc.safe.gate.d": "Einstellungen und Links liegen hinter einem Eltern-Check.",
"abc.safe.hints.t": "Sanfte Tipps",
"abc.safe.hints.d": "Eine Glühbirne hilft in den drei Zuordnungsspielen. Im Bereich Für Eltern lässt sie sich ausschalten.",
"abc.words.eyebrow": "Nächster Schritt: Wörter",
"abc.words.h2": "Buchstaben geschafft? Zeit für Wörter.",
"abc.words.p": "Flip & Learn: Wortkartenspiel kommt aus derselben Familie: 21+ Kategorien, 9 Sprachen, und jedes Wort wird laut vorgesprochen.",
"abc.words.badge": "Von Pädagogen empfohlen bei Google Play",
"abc.words.card": "Hund",
"abc.words.cta": "Entdecke Flip & Learn: Wortkartenspiel",
"abc.print.h2": "Kostenlose Ausmalbilder mit Schreibübungen",
"abc.print.p": "Druck ein Ausmalbild aus und spure das Wort mit dem Stift nach. Danach übst du die Buchstaben im Spiel Buchstaben nachspuren.",
"abc.print.cta": "Zu den Ausmalbildern",
"abc.foot.aria": "Fußzeile",
"abc.foot.motto": "Bildung gehört jedem Kind.",
"abc.foot.words": "Flip & Learn: Wortkartenspiel",
"abc.foot.privacy": "ABC-Datenschutz (auf Englisch)",
},

// French (AI draft). Informal "tu", as on /fr/. ABC game language.
// Game names and "For parents" verbatim from the ABC app (lib/l10n/app_fr.arb);
// Words app name verbatim from Google Play (fr-FR/title.txt).
fr: {
"abc.meta.title": "Flip & Learn ABC — Apprendre l'alphabet en jouant",
"abc.meta.ogalt": "L'icône de l'app Flip & Learn ABC à côté du nom Flip & Learn ABC",
"abc.meta.desc": "Neuf jeux de lettres pour petites mains : associer, tracer, éclater des ballons et nourrir Mo. Les lettres et les mots sont prononcés dans sept langues. Gratuit — sans publicité, sans achats intégrés.",
"abc.nav.aria": "Sections de la page",
"abc.nav.games": "Jeux",
"abc.nav.languages": "Langues",
"abc.nav.parents": "Pour les parents",
"abc.nav.words": "Flip & Learn : Jeu de cartes",
"abc.lang.aria": "Changer la langue de la page",
"abc.hero.h1": "Apprendre l'alphabet en jouant.",
"abc.hero.sub": "Neuf petits jeux de lettres pour petites mains — associer, tracer, éclater des ballons et nourrir Mo le monstre. Les lettres et les mots sont prononcés à voix haute en français, anglais, allemand, espagnol, roumain, hongrois et italien.",
"abc.hero.soon": "Bientôt sur l'App Store et Google Play",
"abc.badge.apple": "Télécharger Flip & Learn ABC sur l'App Store",
"abc.badge.play": "Télécharger Flip & Learn ABC sur Google Play",
"abc.chip.free": "Gratuit",
"abc.chip.ads": "Sans publicité",
"abc.chip.iap": "Sans achats intégrés",
"abc.chip.offline": "Fonctionne hors ligne",
"abc.chip.data": "Aucune collecte de données",
"abc.shot.aria": "Captures d'écran de l'app",
"abc.shot.p1.alt": "Écran d'accueil de Flip & Learn ABC, page 1 : Lettres, Majuscule & minuscule, Mots, Tracer les lettres",
"abc.shot.p2.alt": "Écran d'accueil de Flip & Learn ABC, page 2 : Éclate les ballons, Mo le gourmand, Relie les points, Pêche aux lettres, Paniers de tri",
"abc.shot.prev": "Écran précédent",
"abc.shot.next": "Écran suivant",
"abc.shot.dot1": "Afficher la page 1",
"abc.shot.dot2": "Afficher la page 2",
"abc.langs.eyebrow": "Lettres du monde",
"abc.langs.h2": "Sept alphabets, lettres spéciales comprises.",
"abc.langs.p": "Choisis l'une des sept langues. Ses lettres spéciales, comme Ș, ß, Ñ ou Gy, sont des lettres à part entière dans les jeux. Quand aucun mot ne commence par une lettre, le jeu Mots utilise un mot qui la contient.",
"abc.lang.n26": "26 lettres",
"abc.lang.n27": "27 lettres",
"abc.lang.n30": "30 lettres",
"abc.lang.n31": "31 lettres",
"abc.lang.n44": "44 lettres",
"abc.menus.h3": "Menus en 18 langues",
"abc.menus.p": "Anglais, allemand, espagnol, français, italien, portugais, roumain, hongrois, turc, slovène, néerlandais, bulgare, ukrainien, russe, polonais, tchèque, slovaque et croate. Avec toute autre langue d'appareil, les menus sont en anglais.",
"abc.games.eyebrow": "Neuf jeux, un alphabet",
"abc.games.h2": "Chaque jour, une nouvelle façon de rencontrer les lettres.",
"abc.game.lm.name": "Lettres",
"abc.game.lm.desc": "Retourne les cartes et trouve deux fois la même lettre. Son nom est prononcé à chaque paire.",
"abc.game.cm.name": "Majuscule & minuscule",
"abc.game.cm.desc": "Associe chaque majuscule à sa minuscule.",
"abc.game.wm.name": "Mots",
"abc.game.wm.word": "dauphin",
"abc.game.wm.desc": "Associe une lettre à un mot illustré qui commence par elle — animaux, fruits et bien plus.",
"abc.game.lt.name": "Tracer les lettres",
"abc.game.lt.desc": "Trace chaque lettre avec le doigt, trait par trait. Un point mobile montre d'abord le chemin.",
"abc.game.bp.name": "Éclate les ballons",
"abc.game.bp.desc": "Éclate les ballons qui portent les lettres du mot illustré. Un nouveau mot à chaque partie.",
"abc.game.mo.name": "Mo le gourmand",
"abc.game.mo.desc": "Mo a faim. Donne-lui les images qui commencent par sa lettre — et attends le rot.",
"abc.game.cd.name": "Relie les points",
"abc.game.cd.desc": "Trace de lettre en lettre, dans l'ordre alphabétique. Au dernier point, l'image se colore et prend vie.",
"abc.game.lf.name": "Pêche aux lettres",
"abc.game.lf.desc": "Écoute la lettre, puis touche le poisson qui la porte. Cinq prises font une partie.",
"abc.game.sb.name": "Paniers de tri",
"abc.game.sb.desc": "Glisse chaque image dans le panier de sa première lettre. Rien n'est chronométré.",
"abc.parents.eyebrow": "Pour les parents",
"abc.parents.h2": "Fait par un parent. Sûr dès la conception.",
"abc.parents.p1": "Flip & Learn a commencé comme une app pour mon propre fils. Je développe moi-même chaque app Flip & Learn à Regensburg, en Allemagne, avec le même soin.",
"abc.parents.p2": "Dans Flip & Learn ABC, il n'y a rien à acheter, aucun compte à créer, et l'app ne collecte aucune donnée.",
"abc.parents.privacy": "Lire la politique de confidentialité d'ABC (en anglais)",
"abc.safe.ads.t": "Sans publicité",
"abc.safe.ads.d": "Rien ne sort ton enfant du jeu.",
"abc.safe.iap.t": "Sans achats intégrés",
"abc.safe.iap.d": "Les neuf jeux sont inclus.",
"abc.safe.data.t": "Aucune collecte de données",
"abc.safe.data.d": "L'app n'enregistre que quelques réglages, et seulement sur l'appareil.",
"abc.safe.offline.t": "Fonctionne hors ligne",
"abc.safe.offline.d": "Aucune connexion internet n'est nécessaire pour jouer.",
"abc.safe.gate.t": "Espace parents",
"abc.safe.gate.d": "Les réglages et les liens sont derrière un contrôle parental.",
"abc.safe.hints.t": "Indices en douceur",
"abc.safe.hints.d": "Une ampoule aide dans les trois jeux d'association. Elle se désactive dans l'espace Pour les parents.",
"abc.words.eyebrow": "Étape suivante : les mots",
"abc.words.h2": "Les lettres, c'est fait ? Place aux mots.",
"abc.words.p": "Flip & Learn : Jeu de cartes vient de la même famille : plus de 21 catégories, 9 langues, et chaque mot prononcé à voix haute.",
"abc.words.badge": "Approuvé par les enseignants sur Google Play",
"abc.words.card": "chien",
"abc.words.cta": "Découvre Flip & Learn : Jeu de cartes",
"abc.print.h2": "Fiches de traçage gratuites",
"abc.print.p": "Imprime un coloriage et trace le mot au crayon. Puis entraîne-toi aux lettres dans le jeu Tracer les lettres.",
"abc.print.cta": "Voir les fiches à imprimer",
"abc.foot.aria": "Pied de page",
"abc.foot.motto": "L'éducation appartient à chaque enfant.",
"abc.foot.words": "Flip & Learn : Jeu de cartes",
"abc.foot.privacy": "Confidentialité ABC (en anglais)",
},

// Spanish (AI draft). Informal "tú", as on /es/. ABC game language.
// Game names and "For parents" verbatim from the ABC app (lib/l10n/app_es.arb);
// Words app name verbatim from Google Play (es-ES/title.txt).
es: {
"abc.meta.title": "Flip & Learn ABC — Aprende el abecedario jugando",
"abc.meta.ogalt": "El icono de la app Flip & Learn ABC junto al nombre Flip & Learn ABC",
"abc.meta.desc": "Nueve juegos de letras para manos pequeñas: emparejar, trazar, explotar globos y dar de comer a Mo. Las letras y las palabras se pronuncian en siete idiomas. Gratis — sin anuncios, sin compras en la app.",
"abc.nav.aria": "Secciones de la página",
"abc.nav.games": "Juegos",
"abc.nav.languages": "Idiomas",
"abc.nav.parents": "Para padres",
"abc.nav.words": "Flip & Learn: Juego de cartas",
"abc.lang.aria": "Cambiar el idioma de la página",
"abc.hero.h1": "Aprende el abecedario jugando.",
"abc.hero.sub": "Nueve pequeños juegos de letras para manos pequeñas — emparejar, trazar, explotar globos y dar de comer a Mo, el monstruo. Las letras y las palabras se pronuncian en voz alta en español, inglés, alemán, francés, rumano, húngaro e italiano.",
"abc.hero.soon": "Muy pronto en el App Store y Google Play",
"abc.badge.apple": "Descarga Flip & Learn ABC en el App Store",
"abc.badge.play": "Descarga Flip & Learn ABC en Google Play",
"abc.chip.free": "Gratis",
"abc.chip.ads": "Sin publicidad",
"abc.chip.iap": "Sin compras en la app",
"abc.chip.offline": "Funciona sin conexión",
"abc.chip.data": "Sin recopilación de datos",
"abc.shot.aria": "Capturas de pantalla de la app",
"abc.shot.p1.alt": "Pantalla de inicio de Flip & Learn ABC, página 1: Letras, Mayúscula y minúscula, Palabras, Trazar letras",
"abc.shot.p2.alt": "Pantalla de inicio de Flip & Learn ABC, página 2: Explota globos, Mo el hambriento, Une los puntos, Pesca de letras, Cestas para ordenar",
"abc.shot.prev": "Pantalla anterior",
"abc.shot.next": "Pantalla siguiente",
"abc.shot.dot1": "Mostrar la página 1",
"abc.shot.dot2": "Mostrar la página 2",
"abc.langs.eyebrow": "Letras del mundo",
"abc.langs.h2": "Siete abecedarios, con sus letras especiales.",
"abc.langs.p": "Elige uno de los siete idiomas. Sus letras especiales, como Ș, ß, Ñ o Gy, son letras propias en los juegos. Cuando ninguna palabra empieza por una letra, el juego Palabras usa una palabra que la contiene.",
"abc.lang.n26": "26 letras",
"abc.lang.n27": "27 letras",
"abc.lang.n30": "30 letras",
"abc.lang.n31": "31 letras",
"abc.lang.n44": "44 letras",
"abc.menus.h3": "Menús en 18 idiomas",
"abc.menus.p": "Inglés, alemán, español, francés, italiano, portugués, rumano, húngaro, turco, esloveno, neerlandés, búlgaro, ucraniano, ruso, polaco, checo, eslovaco y croata. Con cualquier otro idioma del dispositivo, los menús aparecen en inglés.",
"abc.games.eyebrow": "Nueve juegos, un abecedario",
"abc.games.h2": "Cada día, una forma nueva de conocer las letras.",
"abc.game.lm.name": "Letras",
"abc.game.lm.desc": "Da la vuelta a las cartas y encuentra dos con la misma letra. En cada pareja se pronuncia su nombre.",
"abc.game.cm.name": "Mayúscula y minúscula",
"abc.game.cm.desc": "Empareja cada mayúscula con su minúscula.",
"abc.game.wm.name": "Palabras",
"abc.game.wm.word": "delfín",
"abc.game.wm.desc": "Empareja una letra con una palabra ilustrada que empieza por ella — animales, frutas y mucho más.",
"abc.game.lt.name": "Trazar letras",
"abc.game.lt.desc": "Traza cada letra con el dedo, trazo a trazo. Antes, un punto en movimiento muestra el camino.",
"abc.game.bp.name": "Explota globos",
"abc.game.bp.desc": "Explota los globos que llevan las letras de la palabra ilustrada. Una palabra nueva en cada partida.",
"abc.game.mo.name": "Mo el hambriento",
"abc.game.mo.desc": "Mo tiene hambre. Dale las imágenes que empiezan por su letra — y espera el eructo.",
"abc.game.cd.name": "Une los puntos",
"abc.game.cd.desc": "Dibuja de letra en letra, en orden alfabético. En el último punto, el dibujo se llena de color y cobra vida.",
"abc.game.lf.name": "Pesca de letras",
"abc.game.lf.desc": "Escucha la letra y toca el pez que la lleva. Cinco capturas hacen una partida.",
"abc.game.sb.name": "Cestas para ordenar",
"abc.game.sb.desc": "Arrastra cada imagen a la cesta de su primera letra. Nada va contrarreloj.",
"abc.parents.eyebrow": "Para padres",
"abc.parents.h2": "Hecho por un padre. Seguro por diseño.",
"abc.parents.p1": "Flip & Learn empezó como una app para mi propio hijo. Desarrollo yo mismo cada app de Flip & Learn en Regensburg, Alemania, con el mismo cuidado.",
"abc.parents.p2": "En Flip & Learn ABC no hay nada que comprar, ninguna cuenta que crear, y la app no recopila datos.",
"abc.parents.privacy": "Lee la política de privacidad de ABC (en inglés)",
"abc.safe.ads.t": "Sin publicidad",
"abc.safe.ads.d": "Nada saca a tu hijo del juego.",
"abc.safe.iap.t": "Sin compras en la app",
"abc.safe.iap.d": "Los nueve juegos están incluidos.",
"abc.safe.data.t": "Sin recopilación de datos",
"abc.safe.data.d": "La app solo guarda unos pocos ajustes, y solo en el dispositivo.",
"abc.safe.offline.t": "Funciona sin conexión",
"abc.safe.offline.d": "No hace falta internet para jugar.",
"abc.safe.gate.t": "Zona para padres",
"abc.safe.gate.d": "Los ajustes y los enlaces están detrás de un control parental.",
"abc.safe.hints.t": "Pistas suaves",
"abc.safe.hints.d": "Una bombilla ayuda en los tres juegos de emparejar. Se puede desactivar en la zona Para padres.",
"abc.words.eyebrow": "Siguiente paso: palabras",
"abc.words.h2": "¿Letras dominadas? Llegan las palabras.",
"abc.words.p": "Flip & Learn: Juego de cartas es de la misma familia: más de 21 categorías, 9 idiomas y cada palabra pronunciada en voz alta.",
"abc.words.badge": "Aprobado por docentes en Google Play",
"abc.words.card": "perro",
"abc.words.cta": "Descubre Flip & Learn: Juego de cartas",
"abc.print.h2": "Fichas gratis para colorear y trazar",
"abc.print.p": "Imprime una ficha para colorear y traza la palabra con un lápiz. Después, practica las letras en el juego Trazar letras.",
"abc.print.cta": "Ver las fichas",
"abc.foot.aria": "Pie de página",
"abc.foot.motto": "La educación es de todos los niños.",
"abc.foot.words": "Flip & Learn: Juego de cartas",
"abc.foot.privacy": "Privacidad de ABC (en inglés)",
},

// Italian (AI draft). Informal "tu", as on /it/. ABC game language.
// Game names and "For parents" verbatim from the ABC app (lib/l10n/app_it.arb);
// Words app name verbatim from Google Play (it-IT/title.txt).
it: {
"abc.meta.title": "Flip & Learn ABC — Impara l'alfabeto giocando",
"abc.meta.ogalt": "L'icona dell'app Flip & Learn ABC accanto al nome Flip & Learn ABC",
"abc.meta.desc": "Nove giochi con le lettere per piccole mani: abbinare, tracciare, scoppiare palloncini e dare da mangiare a Mo. Lettere e parole vengono pronunciate in sette lingue. Gratis — senza pubblicità, senza acquisti in-app.",
"abc.nav.aria": "Sezioni della pagina",
"abc.nav.games": "Giochi",
"abc.nav.languages": "Lingue",
"abc.nav.parents": "Per i genitori",
"abc.nav.words": "Flip & Learn: Gioco di carte",
"abc.lang.aria": "Cambia la lingua della pagina",
"abc.hero.h1": "Impara l'alfabeto giocando.",
"abc.hero.sub": "Nove piccoli giochi con le lettere per piccole mani — abbinare, tracciare, scoppiare palloncini e dare da mangiare a Mo, il mostro. Lettere e parole vengono pronunciate ad alta voce in italiano, inglese, tedesco, spagnolo, francese, rumeno e ungherese.",
"abc.hero.soon": "Presto su App Store e Google Play",
"abc.badge.apple": "Scarica Flip & Learn ABC dall'App Store",
"abc.badge.play": "Scarica Flip & Learn ABC da Google Play",
"abc.chip.free": "Gratis",
"abc.chip.ads": "Senza pubblicità",
"abc.chip.iap": "Senza acquisti in-app",
"abc.chip.offline": "Funziona offline",
"abc.chip.data": "Nessuna raccolta dati",
"abc.shot.aria": "Schermate dell'app",
"abc.shot.p1.alt": "Schermata iniziale di Flip & Learn ABC, pagina 1: Lettere, Maiuscole e minuscole, Parole, Traccia le lettere",
"abc.shot.p2.alt": "Schermata iniziale di Flip & Learn ABC, pagina 2: Scoppia i palloncini, Mo affamato, Unisci i puntini, Pesca le lettere, Cestini da ordinare",
"abc.shot.prev": "Schermata precedente",
"abc.shot.next": "Schermata successiva",
"abc.shot.dot1": "Mostra la pagina 1",
"abc.shot.dot2": "Mostra la pagina 2",
"abc.langs.eyebrow": "Lettere del mondo",
"abc.langs.h2": "Sette alfabeti, lettere speciali comprese.",
"abc.langs.p": "Scegli una delle sette lingue. Le sue lettere speciali, come Ș, ß, Ñ o Gy, nei giochi sono lettere a sé. Quando nessuna parola inizia con una lettera, il gioco Parole usa una parola che la contiene.",
"abc.lang.n26": "26 lettere",
"abc.lang.n27": "27 lettere",
"abc.lang.n30": "30 lettere",
"abc.lang.n31": "31 lettere",
"abc.lang.n44": "44 lettere",
"abc.menus.h3": "Menu in 18 lingue",
"abc.menus.p": "Inglese, tedesco, spagnolo, francese, italiano, portoghese, rumeno, ungherese, turco, sloveno, olandese, bulgaro, ucraino, russo, polacco, ceco, slovacco e croato. Con qualsiasi altra lingua del dispositivo, i menu sono in inglese.",
"abc.games.eyebrow": "Nove giochi, un alfabeto",
"abc.games.h2": "Ogni giorno un modo nuovo di incontrare le lettere.",
"abc.game.lm.name": "Lettere",
"abc.game.lm.desc": "Gira le carte e trova due volte la stessa lettera. A ogni coppia viene pronunciato il suo nome.",
"abc.game.cm.name": "Maiuscole e minuscole",
"abc.game.cm.desc": "Abbina ogni maiuscola alla sua minuscola.",
"abc.game.wm.name": "Parole",
"abc.game.wm.word": "delfino",
"abc.game.wm.desc": "Abbina una lettera a una parola illustrata che inizia con lei — animali, frutta e molto altro.",
"abc.game.lt.name": "Traccia le lettere",
"abc.game.lt.desc": "Traccia ogni lettera con il dito, tratto dopo tratto. Prima, un puntino in movimento mostra il percorso.",
"abc.game.bp.name": "Scoppia i palloncini",
"abc.game.bp.desc": "Scoppia i palloncini che portano le lettere della parola illustrata. Una parola nuova a ogni partita.",
"abc.game.mo.name": "Mo affamato",
"abc.game.mo.desc": "Mo ha fame. Dagli le immagini che iniziano con la sua lettera — e aspetta il ruttino.",
"abc.game.cd.name": "Unisci i puntini",
"abc.game.cd.desc": "Disegna da una lettera all'altra, in ordine alfabetico. All'ultimo puntino l'immagine si colora e prende vita.",
"abc.game.lf.name": "Pesca le lettere",
"abc.game.lf.desc": "Ascolta la lettera, poi tocca il pesce che la porta. Cinque pesci presi fanno una partita.",
"abc.game.sb.name": "Cestini da ordinare",
"abc.game.sb.desc": "Trascina ogni immagine nel cestino della sua prima lettera. Niente è a tempo.",
"abc.parents.eyebrow": "Per i genitori",
"abc.parents.h2": "Fatto da un genitore. Sicuro per scelta.",
"abc.parents.p1": "Flip & Learn è nata come app per mio figlio. Sviluppo personalmente ogni app Flip & Learn a Regensburg, in Germania, con la stessa cura.",
"abc.parents.p2": "In Flip & Learn ABC non c'è niente da comprare, nessun account da creare, e l'app non raccoglie dati.",
"abc.parents.privacy": "Leggi l'informativa sulla privacy di ABC (in inglese)",
"abc.safe.ads.t": "Senza pubblicità",
"abc.safe.ads.d": "Niente distrae tuo figlio dal gioco.",
"abc.safe.iap.t": "Senza acquisti in-app",
"abc.safe.iap.d": "Tutti e nove i giochi sono inclusi.",
"abc.safe.data.t": "Nessuna raccolta dati",
"abc.safe.data.d": "L'app salva solo poche impostazioni, e solo sul dispositivo.",
"abc.safe.offline.t": "Funziona offline",
"abc.safe.offline.d": "Per giocare non serve la connessione a internet.",
"abc.safe.gate.t": "Area genitori",
"abc.safe.gate.d": "Impostazioni e link sono protetti da un controllo genitori.",
"abc.safe.hints.t": "Suggerimenti gentili",
"abc.safe.hints.d": "Una lampadina aiuta nei tre giochi di abbinamento. Si disattiva nell'area Per i genitori.",
"abc.words.eyebrow": "Prossimo passo: le parole",
"abc.words.h2": "Lettere imparate? È il momento delle parole.",
"abc.words.p": "Flip & Learn: Gioco di carte nasce dalla stessa famiglia: oltre 21 categorie, 9 lingue e ogni parola pronunciata ad alta voce.",
"abc.words.badge": "Approvato dagli insegnanti su Google Play",
"abc.words.card": "cane",
"abc.words.cta": "Scopri Flip & Learn: Gioco di carte",
"abc.print.h2": "Schede gratuite da tracciare",
"abc.print.p": "Stampa un disegno da colorare e traccia la parola con la matita. Poi esercitati con le lettere nel gioco Traccia le lettere.",
"abc.print.cta": "Vai alle schede",
"abc.foot.aria": "Piè di pagina",
"abc.foot.motto": "L'istruzione è di ogni bambino.",
"abc.foot.words": "Flip & Learn: Gioco di carte",
"abc.foot.privacy": "Privacy di ABC (in inglese)",
},

// Portuguese, pt-PT (AI draft). Informal "tu", as on /pt/. NOT a game language.
// Game names and "For parents" verbatim from the ABC app (lib/l10n/app_pt.arb);
// Words app name verbatim from Google Play (pt-PT/title.txt).
pt: {
"abc.meta.title": "Flip & Learn ABC — Aprender o alfabeto a brincar, em sete línguas",
"abc.meta.ogalt": "O ícone da app Flip & Learn ABC ao lado do nome Flip & Learn ABC",
"abc.meta.desc": "Nove jogos de letras para mãos pequenas: aprender o alfabeto em inglês, alemão, espanhol, francês, romeno, húngaro ou italiano. Grátis — sem anúncios, sem compras na app.",
"abc.nav.aria": "Secções da página",
"abc.nav.games": "Jogos",
"abc.nav.languages": "Línguas",
"abc.nav.parents": "Para os pais",
"abc.nav.words": "Flip & Learn: Jogo de cartas",
"abc.lang.aria": "Mudar a língua da página",
"abc.hero.h1": "Aprender o alfabeto a brincar, em sete línguas.",
"abc.hero.sub": "Nove pequenos jogos de letras para mãos pequenas — associar, traçar, estourar balões e dar de comer ao Mo, o monstro. As letras e as palavras são ditas em voz alta em inglês, alemão, espanhol, francês, romeno, húngaro ou italiano.",
"abc.hero.soon": "Em breve na App Store e no Google Play",
"abc.badge.apple": "Descarregar Flip & Learn ABC na App Store",
"abc.badge.play": "Descarregar Flip & Learn ABC no Google Play",
"abc.chip.free": "Grátis",
"abc.chip.ads": "Sem publicidade",
"abc.chip.iap": "Sem compras na app",
"abc.chip.offline": "Funciona offline",
"abc.chip.data": "Sem recolha de dados",
"abc.shot.aria": "Capturas de ecrã da app",
"abc.shot.p1.alt": "Ecrã inicial do Flip & Learn ABC, página 1: Letras, Grande e pequena, Palavras, Traçar letras",
"abc.shot.p2.alt": "Ecrã inicial do Flip & Learn ABC, página 2: Estourar balões, Mo com fome, Ligue os pontos, Pesca de letras, Cestas de letras",
"abc.shot.prev": "Ecrã anterior",
"abc.shot.next": "Ecrã seguinte",
"abc.shot.dot1": "Mostrar a página 1",
"abc.shot.dot2": "Mostrar a página 2",
"abc.langs.eyebrow": "Letras do mundo",
"abc.langs.h2": "Sete alfabetos, com as letras especiais.",
"abc.langs.p": "Escolhe uma de sete línguas: inglês, alemão, espanhol, francês, romeno, húngaro ou italiano. As letras especiais, como Ș, ß, Ñ ou Gy, são letras próprias nos jogos. Quando nenhuma palavra começa por uma letra, o jogo Palavras usa uma palavra que a contém. O alfabeto português não faz parte da app; os menus, sim, estão em português.",
"abc.lang.n26": "26 letras",
"abc.lang.n27": "27 letras",
"abc.lang.n30": "30 letras",
"abc.lang.n31": "31 letras",
"abc.lang.n44": "44 letras",
"abc.menus.h3": "Menus em 18 línguas",
"abc.menus.p": "Inglês, alemão, espanhol, francês, italiano, português, romeno, húngaro, turco, esloveno, neerlandês, búlgaro, ucraniano, russo, polaco, checo, eslovaco e croata. Com qualquer outra língua do dispositivo, os menus ficam em inglês.",
"abc.games.eyebrow": "Nove jogos, um alfabeto",
"abc.games.h2": "Todos os dias, uma nova forma de conhecer as letras.",
"abc.game.lm.name": "Letras",
"abc.game.lm.desc": "Vira as cartas e encontra duas com a mesma letra. Em cada par, ouve-se o nome da letra.",
"abc.game.cm.name": "Grande e pequena",
"abc.game.cm.desc": "Junta cada letra grande à sua letra pequena.",
"abc.game.wm.name": "Palavras",
"abc.game.wm.word": "dolphin",
"abc.game.wm.desc": "Junta uma letra a uma palavra ilustrada que começa por ela — animais, frutas e muito mais.",
"abc.game.lt.name": "Traçar letras",
"abc.game.lt.desc": "Traça cada letra com o dedo, traço a traço. Primeiro, um ponto em movimento mostra o caminho.",
"abc.game.bp.name": "Estourar balões",
"abc.game.bp.desc": "Estoura os balões que levam as letras da palavra ilustrada. Uma palavra nova em cada jogo.",
"abc.game.mo.name": "Mo com fome",
"abc.game.mo.desc": "O Mo tem fome. Dá-lhe as imagens que começam pela letra dele — e espera pelo arroto.",
"abc.game.cd.name": "Ligue os pontos",
"abc.game.cd.desc": "Desenha de letra em letra, por ordem alfabética. No último ponto, a imagem enche-se de cor e ganha vida.",
"abc.game.lf.name": "Pesca de letras",
"abc.game.lf.desc": "Ouve a letra e toca no peixe que a leva. Cinco peixes apanhados fazem um jogo.",
"abc.game.sb.name": "Cestas de letras",
"abc.game.sb.desc": "Arrasta cada imagem para a cesta da sua primeira letra. Nada é cronometrado.",
"abc.parents.eyebrow": "Para os pais",
"abc.parents.h2": "Feito por um pai. Seguro de raiz.",
"abc.parents.p1": "O Flip & Learn começou como uma app para o meu próprio filho. Desenvolvo eu mesmo todas as apps Flip & Learn em Regensburg, na Alemanha, com o mesmo cuidado.",
"abc.parents.p2": "No Flip & Learn ABC não há nada para comprar, nenhuma conta para criar, e a app não recolhe dados.",
"abc.parents.privacy": "Ler a política de privacidade do ABC (em inglês)",
"abc.safe.ads.t": "Sem publicidade",
"abc.safe.ads.d": "Nada tira o teu filho do jogo.",
"abc.safe.iap.t": "Sem compras na app",
"abc.safe.iap.d": "Os nove jogos estão incluídos.",
"abc.safe.data.t": "Sem recolha de dados",
"abc.safe.data.d": "A app guarda apenas algumas definições, e só no dispositivo.",
"abc.safe.offline.t": "Funciona offline",
"abc.safe.offline.d": "Não é precisa ligação à internet para jogar.",
"abc.safe.gate.t": "Área dos pais",
"abc.safe.gate.d": "As definições e as ligações ficam atrás de uma verificação parental.",
"abc.safe.hints.t": "Dicas suaves",
"abc.safe.hints.d": "Uma lâmpada ajuda nos três jogos de pares. Pode ser desligada na área Para os pais.",
"abc.words.eyebrow": "Passo seguinte: palavras",
"abc.words.h2": "Letras aprendidas? Hora das palavras.",
"abc.words.p": "Flip & Learn: Jogo de cartas vem da mesma família: mais de 21 categorias, 9 línguas e cada palavra dita em voz alta.",
"abc.words.badge": "Aprovado por professores no Google Play",
"abc.words.card": "cão",
"abc.words.cta": "Descobre Flip & Learn: Jogo de cartas",
"abc.print.h2": "Fichas grátis para traçar",
"abc.print.p": "Imprime uma página para colorir e traça a palavra com um lápis. Depois, pratica as letras no jogo Traçar letras.",
"abc.print.cta": "Ver as fichas",
"abc.foot.aria": "Rodapé",
"abc.foot.motto": "A educação é de todas as crianças.",
"abc.foot.words": "Flip & Learn: Jogo de cartas",
"abc.foot.privacy": "Privacidade do ABC (em inglês)",
},

// Dutch (AI draft). Informal "je", as on /nl/. NOT a game language.
// Game names and "For parents" verbatim from the ABC app (lib/l10n/app_nl.arb);
// Words app name verbatim from Google Play (nl-NL/title.txt).
nl: {
"abc.meta.title": "Flip & Learn ABC — Spelend het alfabet leren, in zeven talen",
"abc.meta.ogalt": "Het app-icoon van Flip & Learn ABC naast de naam Flip & Learn ABC",
"abc.meta.desc": "Negen letterspelletjes voor kleine handen: het alfabet leren in het Engels, Duits, Spaans, Frans, Roemeens, Hongaars of Italiaans. Gratis — geen reclame, geen in-app-aankopen.",
"abc.nav.aria": "Onderdelen van de pagina",
"abc.nav.games": "Spelletjes",
"abc.nav.languages": "Talen",
"abc.nav.parents": "Voor ouders",
"abc.nav.words": "Flip & Learn: Woordkaartspel",
"abc.lang.aria": "Taal van de pagina wijzigen",
"abc.hero.h1": "Spelend het alfabet leren, in zeven talen.",
"abc.hero.sub": "Negen kleine letterspelletjes voor kleine handen — koppelen, overtrekken, ballonnen knallen en Mo het monster voeren. Letters en woorden worden hardop uitgesproken in het Engels, Duits, Spaans, Frans, Roemeens, Hongaars of Italiaans.",
"abc.hero.soon": "Binnenkort in de App Store en op Google Play",
"abc.badge.apple": "Download Flip & Learn ABC in de App Store",
"abc.badge.play": "Download Flip & Learn ABC op Google Play",
"abc.chip.free": "Gratis",
"abc.chip.ads": "Geen reclame",
"abc.chip.iap": "Geen in-app-aankopen",
"abc.chip.offline": "Werkt offline",
"abc.chip.data": "Geen dataverzameling",
"abc.shot.aria": "Schermafbeeldingen van de app",
"abc.shot.p1.alt": "Startscherm van Flip & Learn ABC, pagina 1: Letters, Groot & klein, Woorden, Letters overtrekken",
"abc.shot.p2.alt": "Startscherm van Flip & Learn ABC, pagina 2: Ballonnen knallen, Hongerige Mo, Van stip naar stip, Letters vissen, Sorteermandjes",
"abc.shot.prev": "Vorig scherm",
"abc.shot.next": "Volgend scherm",
"abc.shot.dot1": "Pagina 1 tonen",
"abc.shot.dot2": "Pagina 2 tonen",
"abc.langs.eyebrow": "Letters van de wereld",
"abc.langs.h2": "Zeven alfabetten, inclusief de bijzondere letters.",
"abc.langs.p": "Kies een van de zeven talen: Engels, Duits, Spaans, Frans, Roemeens, Hongaars of Italiaans. De bijzondere letters, zoals Ș, ß, Ñ of Gy, zijn in de spelletjes eigen letters. Begint er geen woord met een letter, dan gebruikt het spel Woorden een woord waar de letter in zit. Het Nederlandse alfabet zit niet in de app; de menu's zijn wel in het Nederlands.",
"abc.lang.n26": "26 letters",
"abc.lang.n27": "27 letters",
"abc.lang.n30": "30 letters",
"abc.lang.n31": "31 letters",
"abc.lang.n44": "44 letters",
"abc.menus.h3": "Menu's in 18 talen",
"abc.menus.p": "Engels, Duits, Spaans, Frans, Italiaans, Portugees, Roemeens, Hongaars, Turks, Sloveens, Nederlands, Bulgaars, Oekraïens, Russisch, Pools, Tsjechisch, Slowaaks en Kroatisch. Bij elke andere toesteltaal zijn de menu's in het Engels.",
"abc.games.eyebrow": "Negen spelletjes, één alfabet",
"abc.games.h2": "Elke dag een nieuwe manier om de letters te ontmoeten.",
"abc.game.lm.name": "Letters",
"abc.game.lm.desc": "Draai de kaarten om en vind twee keer dezelfde letter. Bij elke match hoor je de naam van de letter.",
"abc.game.cm.name": "Groot & klein",
"abc.game.cm.desc": "Zoek bij elke hoofdletter de kleine letter die erbij hoort.",
"abc.game.wm.name": "Woorden",
"abc.game.wm.word": "dolphin",
"abc.game.wm.desc": "Koppel een letter aan een plaatjeswoord dat ermee begint — dieren, fruit en meer.",
"abc.game.lt.name": "Letters overtrekken",
"abc.game.lt.desc": "Trek elke letter over met je vinger, streep voor streep. Eerst wijst een bewegende stip de weg.",
"abc.game.bp.name": "Ballonnen knallen",
"abc.game.bp.desc": "Knal de ballonnen met de letters van het plaatjeswoord. Elk spel een nieuw woord.",
"abc.game.mo.name": "Hongerige Mo",
"abc.game.mo.desc": "Mo heeft honger. Voer hem de plaatjes die met zijn letter beginnen — en wacht op de boer.",
"abc.game.cd.name": "Van stip naar stip",
"abc.game.cd.desc": "Teken van letter naar letter, in de volgorde van het alfabet. Bij de laatste stip kleurt het plaatje in en komt het tot leven.",
"abc.game.lf.name": "Letters vissen",
"abc.game.lf.desc": "Luister naar de letter en tik dan op de vis die hem draagt. Vijf vangsten zijn één spel.",
"abc.game.sb.name": "Sorteermandjes",
"abc.game.sb.desc": "Sleep elk plaatje naar het mandje van zijn eerste letter. Er loopt geen klok mee.",
"abc.parents.eyebrow": "Voor ouders",
"abc.parents.h2": "Gemaakt door een ouder. Veilig van opzet.",
"abc.parents.p1": "Flip & Learn begon als een app voor mijn eigen zoon. Elke Flip & Learn-app bouw ik zelf in Regensburg, Duitsland, met dezelfde zorg.",
"abc.parents.p2": "In Flip & Learn ABC valt niets te kopen, je hoeft geen account te maken en de app verzamelt geen gegevens.",
"abc.parents.privacy": "Lees het privacybeleid van ABC (in het Engels)",
"abc.safe.ads.t": "Geen reclame",
"abc.safe.ads.d": "Niets haalt je kind uit het spel.",
"abc.safe.iap.t": "Geen in-app-aankopen",
"abc.safe.iap.d": "Alle negen spelletjes zitten erin.",
"abc.safe.data.t": "Geen dataverzameling",
"abc.safe.data.d": "De app bewaart alleen een paar instellingen, en alleen op het toestel.",
"abc.safe.offline.t": "Werkt offline",
"abc.safe.offline.d": "Om te spelen is geen internetverbinding nodig.",
"abc.safe.gate.t": "Oudergedeelte",
"abc.safe.gate.d": "Instellingen en links zitten achter een oudercheck.",
"abc.safe.hints.t": "Zachte hints",
"abc.safe.hints.d": "Een lampje helpt in de drie koppelspelletjes. Uitzetten kan in het gedeelte Voor ouders.",
"abc.words.eyebrow": "Volgende stap: woorden",
"abc.words.h2": "Letters onder de knie? Tijd voor woorden.",
"abc.words.p": "Flip & Learn: Woordkaartspel komt uit dezelfde familie: 21+ categorieën, 9 talen, en elk woord wordt hardop uitgesproken.",
"abc.words.badge": "Goedgekeurd door leerkrachten op Google Play",
"abc.words.card": "dog",
"abc.words.cta": "Ontdek Flip & Learn: Woordkaartspel",
"abc.print.h2": "Gratis overtrekbladen",
"abc.print.p": "Print een kleurplaat en trek het woord over met een potlood. Oefen daarna de letters in het spel Letters overtrekken.",
"abc.print.cta": "Naar de printbladen",
"abc.foot.aria": "Voettekst",
"abc.foot.motto": "Onderwijs is er voor elk kind.",
"abc.foot.words": "Flip & Learn: Woordkaartspel",
"abc.foot.privacy": "ABC-privacy (in het Engels)",
},

// Polish (AI draft). Addresses the parent as "Ty", as on /pl/. NOT a game language.
// Game names and "For parents" verbatim from the ABC app (lib/l10n/app_pl.arb);
// Words app name verbatim from Google Play (pl-PL/title.txt).
pl: {
"abc.meta.title": "Flip & Learn ABC — Nauka alfabetu przez zabawę, w siedmiu językach",
"abc.meta.ogalt": "Ikona aplikacji Flip & Learn ABC obok nazwy Flip & Learn ABC",
"abc.meta.desc": "Dziewięć gier z literami dla małych rączek: nauka alfabetu po angielsku, niemiecku, hiszpańsku, francusku, rumuńsku, węgiersku lub włosku. Bezpłatnie — bez reklam, bez zakupów w aplikacji.",
"abc.nav.aria": "Sekcje strony",
"abc.nav.games": "Gry",
"abc.nav.languages": "Języki",
"abc.nav.parents": "Dla rodziców",
"abc.nav.words": "Flip & Learn: Gra ze słówkami",
"abc.lang.aria": "Zmień język strony",
"abc.hero.h1": "Nauka alfabetu przez zabawę, w siedmiu językach.",
"abc.hero.sub": "Dziewięć małych gier z literami dla małych rączek — dobieranie w pary, pisanie po śladzie, pękające balony i karmienie potworka Mo. Litery i słowa są wymawiane na głos po angielsku, niemiecku, hiszpańsku, francusku, rumuńsku, węgiersku lub włosku.",
"abc.hero.soon": "Wkrótce w App Store i Google Play",
"abc.badge.apple": "Pobierz Flip & Learn ABC z App Store",
"abc.badge.play": "Pobierz Flip & Learn ABC z Google Play",
"abc.chip.free": "Bezpłatnie",
"abc.chip.ads": "Bez reklam",
"abc.chip.iap": "Bez zakupów w aplikacji",
"abc.chip.offline": "Działa offline",
"abc.chip.data": "Brak zbierania danych",
"abc.shot.aria": "Zrzuty ekranu aplikacji",
"abc.shot.p1.alt": "Ekran główny Flip & Learn ABC, strona 1: Litery, Wielkie i małe, Słowa, Pisanie liter",
"abc.shot.p2.alt": "Ekran główny Flip & Learn ABC, strona 2: Pękające balony, Głodny Mo, Połącz kropki, Łowienie liter, Koszyki z literami",
"abc.shot.prev": "Poprzedni ekran",
"abc.shot.next": "Następny ekran",
"abc.shot.dot1": "Pokaż stronę 1",
"abc.shot.dot2": "Pokaż stronę 2",
"abc.langs.eyebrow": "Litery świata",
"abc.langs.h2": "Siedem alfabetów, razem ze znakami specjalnymi.",
"abc.langs.p": "Wybierz jeden z siedmiu języków: angielski, niemiecki, hiszpański, francuski, rumuński, węgierski lub włoski. Litery specjalne, takie jak Ș, ß, Ñ czy Gy, są w grach osobnymi literami. Gdy żadne słowo nie zaczyna się na daną literę, gra Słowa pokazuje słowo, które ją zawiera. Polskiego alfabetu w aplikacji nie ma; po polsku jest menu.",
"abc.lang.n26": "26 liter",
"abc.lang.n27": "27 liter",
"abc.lang.n30": "30 liter",
"abc.lang.n31": "31 liter",
"abc.lang.n44": "44 litery",
"abc.menus.h3": "Menu w 18 językach",
"abc.menus.p": "Angielski, niemiecki, hiszpański, francuski, włoski, portugalski, rumuński, węgierski, turecki, słoweński, niderlandzki, bułgarski, ukraiński, rosyjski, polski, czeski, słowacki i chorwacki. Przy każdym innym języku urządzenia menu jest po angielsku.",
"abc.games.eyebrow": "Dziewięć gier, jeden alfabet",
"abc.games.h2": "Codziennie nowy sposób na spotkanie z literami.",
"abc.game.lm.name": "Litery",
"abc.game.lm.desc": "Odwracaj karty i znajdź dwie z tą samą literą. Przy każdej parze słychać nazwę litery.",
"abc.game.cm.name": "Wielkie i małe",
"abc.game.cm.desc": "Połącz każdą wielką literę z jej małą parą.",
"abc.game.wm.name": "Słowa",
"abc.game.wm.word": "dolphin",
"abc.game.wm.desc": "Połącz literę z obrazkiem i słowem, które się na nią zaczyna — zwierzęta, owoce i nie tylko.",
"abc.game.lt.name": "Pisanie liter",
"abc.game.lt.desc": "Pisz każdą literę palcem, kreska po kresce. Najpierw ruchoma kropka pokazuje drogę.",
"abc.game.bp.name": "Pękające balony",
"abc.game.bp.desc": "Przebijaj balony z literami słowa z obrazka. W każdej grze nowe słowo.",
"abc.game.mo.name": "Głodny Mo",
"abc.game.mo.desc": "Mo jest głodny. Nakarm go obrazkami, które zaczynają się na jego literę — i poczekaj, aż mu się odbije.",
"abc.game.cd.name": "Połącz kropki",
"abc.game.cd.desc": "Rysuj od litery do litery, w kolejności alfabetu. Przy ostatniej kropce obrazek wypełnia się kolorem i ożywa.",
"abc.game.lf.name": "Łowienie liter",
"abc.game.lf.desc": "Posłuchaj litery, a potem dotknij rybki, która ją niesie. Pięć złowionych rybek to jedna gra.",
"abc.game.sb.name": "Koszyki z literami",
"abc.game.sb.desc": "Przeciągnij każdy obrazek do koszyka z jego pierwszą literą. Nic nie jest na czas.",
"abc.parents.eyebrow": "Dla rodziców",
"abc.parents.h2": "Stworzona przez rodzica. Bezpieczna z założenia.",
"abc.parents.p1": "Flip & Learn zaczęło się jako aplikacja dla mojego syna. Każdą aplikację Flip & Learn tworzę sam w Ratyzbonie w Niemczech, z taką samą starannością.",
"abc.parents.p2": "W Flip & Learn ABC nie ma nic do kupienia, nie trzeba zakładać konta, a aplikacja nie zbiera danych.",
"abc.parents.privacy": "Przeczytaj politykę prywatności ABC (po angielsku)",
"abc.safe.ads.t": "Bez reklam",
"abc.safe.ads.d": "Nic nie odrywa Twojego dziecka od gry.",
"abc.safe.iap.t": "Bez zakupów w aplikacji",
"abc.safe.iap.d": "Wszystkie dziewięć gier jest w zestawie.",
"abc.safe.data.t": "Brak zbierania danych",
"abc.safe.data.d": "Aplikacja zapisuje tylko kilka ustawień, i to wyłącznie na urządzeniu.",
"abc.safe.offline.t": "Działa offline",
"abc.safe.offline.d": "Do gry nie jest potrzebny internet.",
"abc.safe.gate.t": "Strefa rodziców",
"abc.safe.gate.d": "Ustawienia i linki są za kontrolą rodzicielską.",
"abc.safe.hints.t": "Delikatne podpowiedzi",
"abc.safe.hints.d": "Żarówka pomaga w trzech grach w dobieranie par. Można ją wyłączyć w części Dla rodziców.",
"abc.words.eyebrow": "Następny krok: słowa",
"abc.words.h2": "Litery opanowane? Czas na słowa.",
"abc.words.p": "Flip & Learn: Gra ze słówkami pochodzi z tej samej rodziny: ponad 21 kategorii, 9 języków, a każde słowo jest wymawiane na głos.",
"abc.words.badge": "Zatwierdzone przez nauczycieli w Google Play",
"abc.words.card": "dog",
"abc.words.cta": "Poznaj aplikację Flip & Learn: Gra ze słówkami",
"abc.print.h2": "Bezpłatne karty do pisania po śladzie",
"abc.print.p": "Wydrukuj kolorowankę i napisz słowo ołówkiem po śladzie. Potem poćwicz litery w grze Pisanie liter.",
"abc.print.cta": "Zobacz karty do druku",
"abc.foot.aria": "Stopka",
"abc.foot.motto": "Edukacja należy się każdemu dziecku.",
"abc.foot.words": "Flip & Learn: Gra ze słówkami",
"abc.foot.privacy": "Prywatność ABC (po angielsku)",
},

// Turkish (AI draft). Informal "sen", as on /tr/. NOT a game language.
// Game names and "For parents" verbatim from the ABC app (lib/l10n/app_tr.arb);
// Words app name verbatim from Google Play (tr-TR/title.txt).
tr: {
"abc.meta.title": "Flip & Learn ABC — Oynayarak alfabe öğren, yedi dilde",
"abc.meta.ogalt": "Flip & Learn ABC uygulama simgesi, yanında Flip & Learn ABC adı",
"abc.meta.desc": "Küçük eller için dokuz harf oyunu: alfabeyi İngilizce, Almanca, İspanyolca, Fransızca, Rumence, Macarca veya İtalyanca öğren. Ücretsiz — reklam yok, uygulama içi satın alma yok.",
"abc.nav.aria": "Sayfa bölümleri",
"abc.nav.games": "Oyunlar",
"abc.nav.languages": "Diller",
"abc.nav.parents": "Ebeveynler için",
"abc.nav.words": "Flip & Learn: Kelime Kartları",
"abc.lang.aria": "Sayfa dilini değiştir",
"abc.hero.h1": "Oynayarak alfabe öğren, yedi dilde.",
"abc.hero.sub": "Küçük eller için dokuz küçük harf oyunu — eşleştirme, harf çizme, balon patlatma ve canavar Mo'yu besleme. Harfler ve kelimeler İngilizce, Almanca, İspanyolca, Fransızca, Rumence, Macarca veya İtalyanca yüksek sesle söylenir.",
"abc.hero.soon": "Yakında App Store ve Google Play'de",
"abc.badge.apple": "App Store'dan indir: Flip & Learn ABC",
"abc.badge.play": "Google Play'den indir: Flip & Learn ABC",
"abc.chip.free": "Ücretsiz",
"abc.chip.ads": "Reklam yok",
"abc.chip.iap": "Uygulama içi satın alma yok",
"abc.chip.offline": "Çevrimdışı çalışır",
"abc.chip.data": "Veri toplama yok",
"abc.shot.aria": "Uygulamadan ekran görüntüleri",
"abc.shot.p1.alt": "Flip & Learn ABC ana ekranı, 1. sayfa: Harfler, Büyük ve küçük, Kelimeler, Harf Çizme",
"abc.shot.p2.alt": "Flip & Learn ABC ana ekranı, 2. sayfa: Balon Patlatma, Aç Mo, Noktaları Birleştir, Harf Avı, Sepetlere Ayır",
"abc.shot.prev": "Önceki ekran",
"abc.shot.next": "Sonraki ekran",
"abc.shot.dot1": "1. sayfayı göster",
"abc.shot.dot2": "2. sayfayı göster",
"abc.langs.eyebrow": "Dünyanın harfleri",
"abc.langs.h2": "Yedi alfabe, özel harfleriyle birlikte.",
"abc.langs.p": "Yedi dilden birini seç: İngilizce, Almanca, İspanyolca, Fransızca, Rumence, Macarca veya İtalyanca. Ș, ß, Ñ veya Gy gibi özel harfler oyunlarda ayrı birer harftir. Bir harfle başlayan kelime yoksa Kelimeler oyunu o harfi içeren bir kelime kullanır. Türk alfabesi uygulamada yok; menüler ise Türkçe.",
"abc.lang.n26": "26 harf",
"abc.lang.n27": "27 harf",
"abc.lang.n30": "30 harf",
"abc.lang.n31": "31 harf",
"abc.lang.n44": "44 harf",
"abc.menus.h3": "18 dilde menü",
"abc.menus.p": "İngilizce, Almanca, İspanyolca, Fransızca, İtalyanca, Portekizce, Rumence, Macarca, Türkçe, Slovence, Felemenkçe, Bulgarca, Ukraynaca, Rusça, Lehçe, Çekçe, Slovakça ve Hırvatça. Cihazın dili bunlardan biri değilse menüler İngilizce görünür.",
"abc.games.eyebrow": "Dokuz oyun, bir alfabe",
"abc.games.h2": "Her gün harflerle tanışmanın yeni bir yolu.",
"abc.game.lm.name": "Harfler",
"abc.game.lm.desc": "Kartları çevir ve aynı harften iki tane bul. Her eşleşmede harfin adı söylenir.",
"abc.game.cm.name": "Büyük ve küçük",
"abc.game.cm.desc": "Her büyük harfi küçük eşiyle eşleştir.",
"abc.game.wm.name": "Kelimeler",
"abc.game.wm.word": "dolphin",
"abc.game.wm.desc": "Bir harfi, o harfle başlayan resimli bir kelimeyle eşleştir — hayvanlar, meyveler ve daha fazlası.",
"abc.game.lt.name": "Harf Çizme",
"abc.game.lt.desc": "Her harfi parmağınla, çizgi çizgi çiz. Önce hareketli bir nokta yolu gösterir.",
"abc.game.bp.name": "Balon Patlatma",
"abc.game.bp.desc": "Resimdeki kelimenin harflerini taşıyan balonları patlat. Her oyunda yeni bir kelime.",
"abc.game.mo.name": "Aç Mo",
"abc.game.mo.desc": "Mo acıktı. Ona kendi harfiyle başlayan resimleri ver — ve geğirmesini bekle.",
"abc.game.cd.name": "Noktaları Birleştir",
"abc.game.cd.desc": "Alfabe sırasıyla harften harfe çiz. Son noktada resim renklenir ve canlanır.",
"abc.game.lf.name": "Harf Avı",
"abc.game.lf.desc": "Harfi dinle, sonra onu taşıyan balığa dokun. Beş av bir oyun eder.",
"abc.game.sb.name": "Sepetlere Ayır",
"abc.game.sb.desc": "Her resmi ilk harfinin sepetine sürükle. Süre tutulmaz.",
"abc.parents.eyebrow": "Ebeveynler için",
"abc.parents.h2": "Bir ebeveyn yaptı. Baştan güvenli tasarlandı.",
"abc.parents.p1": "Flip & Learn, kendi oğlum için bir uygulama olarak başladı. Her Flip & Learn uygulamasını Almanya'nın Regensburg şehrinde, aynı özenle kendim geliştiriyorum.",
"abc.parents.p2": "Flip & Learn ABC içinde satın alınacak bir şey yok, hesap açmak gerekmiyor ve uygulama veri toplamıyor.",
"abc.parents.privacy": "ABC gizlilik politikasını oku (İngilizce)",
"abc.safe.ads.t": "Reklam yok",
"abc.safe.ads.d": "Hiçbir şey çocuğunu oyundan koparmaz.",
"abc.safe.iap.t": "Uygulama içi satın alma yok",
"abc.safe.iap.d": "Dokuz oyunun hepsi dahil.",
"abc.safe.data.t": "Veri toplama yok",
"abc.safe.data.d": "Uygulama yalnızca birkaç ayarı, o da sadece cihazda saklar.",
"abc.safe.offline.t": "Çevrimdışı çalışır",
"abc.safe.offline.d": "Oynamak için internet bağlantısı gerekmez.",
"abc.safe.gate.t": "Ebeveyn alanı",
"abc.safe.gate.d": "Ayarlar ve bağlantılar ebeveyn kontrolünün arkasında.",
"abc.safe.hints.t": "Nazik ipuçları",
"abc.safe.hints.d": "Üç eşleştirme oyununda bir ampul yardım eder. Ebeveynler için alanından kapatılabilir.",
"abc.words.eyebrow": "Sıradaki adım: kelimeler",
"abc.words.h2": "Harfler tamam mı? Sıra kelimelerde.",
"abc.words.p": "Flip & Learn: Kelime Kartları aynı aileden geliyor: 21+ kategori, 9 dil ve her kelime sesli okunuyor.",
"abc.words.badge": "Google Play'de Öğretmen Onaylı",
"abc.words.card": "dog",
"abc.words.cta": "Flip & Learn: Kelime Kartları uygulamasını keşfet",
"abc.print.h2": "Ücretsiz çizgi çalışma sayfaları",
"abc.print.p": "Bir boyama sayfası yazdır ve kelimenin üzerinden kalemle geç. Sonra harfleri Harf Çizme oyununda çalış.",
"abc.print.cta": "Yazdırılabilir sayfalara git",
"abc.foot.aria": "Alt bilgi",
"abc.foot.motto": "Eğitim her çocuğun hakkıdır.",
"abc.foot.words": "Flip & Learn: Kelime Kartları",
"abc.foot.privacy": "ABC gizliliği (İngilizce)",
},

// Czech (AI draft). Formal "vy", as on /cs/; game cards are descriptive. NOT a game language.
// Game names and "For parents" verbatim from the ABC app (lib/l10n/app_cs.arb);
// Words app name verbatim from Google Play (cs-CZ/title.txt).
cs: {
"abc.meta.title": "Flip & Learn ABC — Abeceda hrou, v sedmi jazycích",
"abc.meta.ogalt": "Ikona aplikace Flip & Learn ABC vedle názvu Flip & Learn ABC",
"abc.meta.desc": "Devět her s písmeny pro malé ruce: abeceda v angličtině, němčině, španělštině, francouzštině, rumunštině, maďarštině nebo italštině. Zdarma — bez reklam, bez nákupů v aplikaci.",
"abc.nav.aria": "Části stránky",
"abc.nav.games": "Hry",
"abc.nav.languages": "Jazyky",
"abc.nav.parents": "Pro rodiče",
"abc.nav.words": "Flip & Learn: Hra s kartičkami",
"abc.lang.aria": "Změnit jazyk stránky",
"abc.hero.h1": "Abeceda hrou, v sedmi jazycích.",
"abc.hero.sub": "Devět malých her s písmeny pro malé ruce — hledání dvojic, psaní písmen, praskání balónků a krmení příšerky Mo. Písmena a slova zaznívají nahlas v angličtině, němčině, španělštině, francouzštině, rumunštině, maďarštině nebo italštině.",
"abc.hero.soon": "Již brzy v App Storu a na Google Play",
"abc.badge.apple": "Stáhnout Flip & Learn ABC z App Storu",
"abc.badge.play": "Stáhnout Flip & Learn ABC z Google Play",
"abc.chip.free": "Zdarma",
"abc.chip.ads": "Žádné reklamy",
"abc.chip.iap": "Žádné nákupy v aplikaci",
"abc.chip.offline": "Funguje offline",
"abc.chip.data": "Žádný sběr dat",
"abc.shot.aria": "Snímky obrazovky z aplikace",
"abc.shot.p1.alt": "Domovská obrazovka Flip & Learn ABC, strana 1: Písmena, Velká a malá, Slova, Psaní písmen",
"abc.shot.p2.alt": "Domovská obrazovka Flip & Learn ABC, strana 2: Praskání balónků, Hladový Mo, Spojovačka, Lov písmen, Třídění do košíků",
"abc.shot.prev": "Předchozí obrazovka",
"abc.shot.next": "Další obrazovka",
"abc.shot.dot1": "Zobrazit stranu 1",
"abc.shot.dot2": "Zobrazit stranu 2",
"abc.langs.eyebrow": "Písmena světa",
"abc.langs.h2": "Sedm abeced, včetně zvláštních písmen.",
"abc.langs.p": "Vyberte si jeden ze sedmi jazyků: angličtinu, němčinu, španělštinu, francouzštinu, rumunštinu, maďarštinu nebo italštinu. Zvláštní písmena jako Ș, ß, Ñ nebo Gy jsou ve hrách samostatnými písmeny. Když na některé písmeno nezačíná žádné slovo, použije hra Slova slovo, které ho obsahuje. Českou abecedu aplikace neobsahuje; v češtině jsou nabídky.",
"abc.lang.n26": "26 písmen",
"abc.lang.n27": "27 písmen",
"abc.lang.n30": "30 písmen",
"abc.lang.n31": "31 písmen",
"abc.lang.n44": "44 písmen",
"abc.menus.h3": "Nabídky v 18 jazycích",
"abc.menus.p": "Angličtina, němčina, španělština, francouzština, italština, portugalština, rumunština, maďarština, turečtina, slovinština, nizozemština, bulharština, ukrajinština, ruština, polština, čeština, slovenština a chorvatština. Při jakémkoli jiném jazyce zařízení jsou nabídky v angličtině.",
"abc.games.eyebrow": "Devět her, jedna abeceda",
"abc.games.h2": "Každý den nové setkání s písmeny.",
"abc.game.lm.name": "Písmena",
"abc.game.lm.desc": "Dítě otáčí kartičky a hledá dvě se stejným písmenem. Při každé dvojici zazní název písmene.",
"abc.game.cm.name": "Velká a malá",
"abc.game.cm.desc": "Ke každému velkému písmenu se hledá jeho malé.",
"abc.game.wm.name": "Slova",
"abc.game.wm.word": "dolphin",
"abc.game.wm.desc": "K písmenu patří obrázek se slovem, které na něj začíná — zvířata, ovoce a další.",
"abc.game.lt.name": "Psaní písmen",
"abc.game.lt.desc": "Každé písmeno se píše prstem, tah po tahu. Nejdřív cestu ukáže pohyblivá tečka.",
"abc.game.bp.name": "Praskání balónků",
"abc.game.bp.desc": "Praskají se balónky s písmeny slova z obrázku. V každé hře nové slovo.",
"abc.game.mo.name": "Hladový Mo",
"abc.game.mo.desc": "Mo má hlad. Dostává obrázky, které začínají na jeho písmeno — a na konci si říhne.",
"abc.game.cd.name": "Spojovačka",
"abc.game.cd.desc": "Kreslí se od písmene k písmenu podle abecedy. U poslední tečky se obrázek vybarví a ožije.",
"abc.game.lf.name": "Lov písmen",
"abc.game.lf.desc": "Zazní písmeno a dítě ťukne na rybu, která ho nese. Pět úlovků je jedna hra.",
"abc.game.sb.name": "Třídění do košíků",
"abc.game.sb.desc": "Každý obrázek patří do košíku se svým prvním písmenem. Nic se neměří na čas.",
"abc.parents.eyebrow": "Pro rodiče",
"abc.parents.h2": "Vytvořil rodič. Bezpečná už od návrhu.",
"abc.parents.p1": "Flip & Learn začal jako aplikace pro mého vlastního syna. Každou aplikaci Flip & Learn vytvářím sám v německém Řezně, se stejnou péčí.",
"abc.parents.p2": "Ve Flip & Learn ABC není co kupovat, není třeba se registrovat a aplikace nesbírá žádná data.",
"abc.parents.privacy": "Přečtěte si zásady ochrany soukromí ABC (v angličtině)",
"abc.safe.ads.t": "Žádné reklamy",
"abc.safe.ads.d": "Nic vaše dítě neodvádí od hry.",
"abc.safe.iap.t": "Žádné nákupy v aplikaci",
"abc.safe.iap.d": "Všech devět her je součástí.",
"abc.safe.data.t": "Žádný sběr dat",
"abc.safe.data.d": "Aplikace ukládá jen několik nastavení, a to pouze v zařízení.",
"abc.safe.offline.t": "Funguje offline",
"abc.safe.offline.d": "Ke hraní není potřeba připojení k internetu.",
"abc.safe.gate.t": "Část pro rodiče",
"abc.safe.gate.d": "Nastavení a odkazy jsou za kontrolou pro rodiče.",
"abc.safe.hints.t": "Jemné nápovědy",
"abc.safe.hints.d": "Ve třech hrách s dvojicemi pomáhá žárovka. Vypnout ji lze v části Pro rodiče.",
"abc.words.eyebrow": "Další krok: slova",
"abc.words.h2": "Písmena zvládnutá? Čas na slova.",
"abc.words.p": "Flip & Learn: Hra s kartičkami je ze stejné rodiny: 21+ kategorií, 9 jazyků a každé slovo zazní nahlas.",
"abc.words.badge": "Schváleno učiteli na Google Play",
"abc.words.card": "dog",
"abc.words.cta": "Objevte aplikaci Flip & Learn: Hra s kartičkami",
"abc.print.h2": "Pracovní listy na psaní zdarma",
"abc.print.p": "Vytiskněte omalovánku a obtáhněte slovo tužkou. Písmena pak lze procvičit ve hře Psaní písmen.",
"abc.print.cta": "Zobrazit pracovní listy",
"abc.foot.aria": "Zápatí",
"abc.foot.motto": "Vzdělání patří každému dítěti.",
"abc.foot.words": "Flip & Learn: Hra s kartičkami",
"abc.foot.privacy": "Soukromí ABC (anglicky)",
},

// Slovak (AI draft). Formal "vy", as on /sk/; game cards are descriptive. NOT a game language.
// Game names and "For parents" verbatim from the ABC app (lib/l10n/app_sk.arb);
// Words app name verbatim from Google Play (sk/title.txt).
sk: {
"abc.meta.title": "Flip & Learn ABC — Abeceda hrou, v siedmich jazykoch",
"abc.meta.ogalt": "Ikona aplikácie Flip & Learn ABC vedľa názvu Flip & Learn ABC",
"abc.meta.desc": "Deväť hier s písmenami pre malé ruky: abeceda v angličtine, nemčine, španielčine, francúzštine, rumunčine, maďarčine alebo taliančine. Zadarmo — bez reklám, bez nákupov v aplikácii.",
"abc.nav.aria": "Časti stránky",
"abc.nav.games": "Hry",
"abc.nav.languages": "Jazyky",
"abc.nav.parents": "Pre rodičov",
"abc.nav.words": "Flip & Learn: Hra s kartami",
"abc.lang.aria": "Zmeniť jazyk stránky",
"abc.hero.h1": "Abeceda hrou, v siedmich jazykoch.",
"abc.hero.sub": "Deväť malých hier s písmenami pre malé ruky — hľadanie dvojíc, písanie písmen, praskanie balónov a kŕmenie príšerky Mo. Písmená a slová zaznievajú nahlas v angličtine, nemčine, španielčine, francúzštine, rumunčine, maďarčine alebo taliančine.",
"abc.hero.soon": "Už čoskoro v App Store a na Google Play",
"abc.badge.apple": "Stiahnuť Flip & Learn ABC z App Store",
"abc.badge.play": "Stiahnuť Flip & Learn ABC z Google Play",
"abc.chip.free": "Zadarmo",
"abc.chip.ads": "Žiadne reklamy",
"abc.chip.iap": "Žiadne nákupy v aplikácii",
"abc.chip.offline": "Funguje offline",
"abc.chip.data": "Žiadny zber dát",
"abc.shot.aria": "Snímky obrazovky z aplikácie",
"abc.shot.p1.alt": "Domovská obrazovka Flip & Learn ABC, strana 1: Písmená, Veľké a malé, Slová, Písanie písmen",
"abc.shot.p2.alt": "Domovská obrazovka Flip & Learn ABC, strana 2: Praskanie balónov, Hladný Mo, Spoj bodky, Lov písmen, Triedenie do košíkov",
"abc.shot.prev": "Predchádzajúca obrazovka",
"abc.shot.next": "Ďalšia obrazovka",
"abc.shot.dot1": "Zobraziť stranu 1",
"abc.shot.dot2": "Zobraziť stranu 2",
"abc.langs.eyebrow": "Písmená sveta",
"abc.langs.h2": "Sedem abecied, vrátane zvláštnych písmen.",
"abc.langs.p": "Vyberte si jeden zo siedmich jazykov: angličtinu, nemčinu, španielčinu, francúzštinu, rumunčinu, maďarčinu alebo taliančinu. Zvláštne písmená ako Ș, ß, Ñ alebo Gy sú v hrách samostatnými písmenami. Keď sa na niektoré písmeno nezačína žiadne slovo, hra Slová použije slovo, ktoré ho obsahuje. Slovenskú abecedu aplikácia neobsahuje; v slovenčine sú ponuky.",
"abc.lang.n26": "26 písmen",
"abc.lang.n27": "27 písmen",
"abc.lang.n30": "30 písmen",
"abc.lang.n31": "31 písmen",
"abc.lang.n44": "44 písmen",
"abc.menus.h3": "Ponuky v 18 jazykoch",
"abc.menus.p": "Angličtina, nemčina, španielčina, francúzština, taliančina, portugalčina, rumunčina, maďarčina, turečtina, slovinčina, holandčina, bulharčina, ukrajinčina, ruština, poľština, čeština, slovenčina a chorvátčina. Pri akomkoľvek inom jazyku zariadenia sú ponuky v angličtine.",
"abc.games.eyebrow": "Deväť hier, jedna abeceda",
"abc.games.h2": "Každý deň nové stretnutie s písmenami.",
"abc.game.lm.name": "Písmená",
"abc.game.lm.desc": "Dieťa otáča kartičky a hľadá dve s rovnakým písmenom. Pri každej dvojici zaznie názov písmena.",
"abc.game.cm.name": "Veľké a malé",
"abc.game.cm.desc": "Ku každému veľkému písmenu sa hľadá jeho malé.",
"abc.game.wm.name": "Slová",
"abc.game.wm.word": "dolphin",
"abc.game.wm.desc": "K písmenu patrí obrázok so slovom, ktoré sa naň začína — zvieratá, ovocie a ďalšie.",
"abc.game.lt.name": "Písanie písmen",
"abc.game.lt.desc": "Každé písmeno sa píše prstom, ťah po ťahu. Najprv cestu ukáže pohyblivá bodka.",
"abc.game.bp.name": "Praskanie balónov",
"abc.game.bp.desc": "Praskajú sa balóny s písmenami slova z obrázka. V každej hre nové slovo.",
"abc.game.mo.name": "Hladný Mo",
"abc.game.mo.desc": "Mo je hladný. Dostáva obrázky, ktoré sa začínajú na jeho písmeno — a na konci si grgne.",
"abc.game.cd.name": "Spoj bodky",
"abc.game.cd.desc": "Kreslí sa od písmena k písmenu podľa abecedy. Pri poslednej bodke sa obrázok vyfarbí a ožije.",
"abc.game.lf.name": "Lov písmen",
"abc.game.lf.desc": "Zaznie písmeno a dieťa ťukne na rybu, ktorá ho nesie. Päť úlovkov je jedna hra.",
"abc.game.sb.name": "Triedenie do košíkov",
"abc.game.sb.desc": "Každý obrázok patrí do košíka so svojím prvým písmenom. Nič sa nemeria na čas.",
"abc.parents.eyebrow": "Pre rodičov",
"abc.parents.h2": "Vytvoril rodič. Bezpečná už od návrhu.",
"abc.parents.p1": "Flip & Learn sa začal ako aplikácia pre môjho vlastného syna. Každú aplikáciu Flip & Learn vytváram sám v nemeckom Regensburgu, s rovnakou starostlivosťou.",
"abc.parents.p2": "Vo Flip & Learn ABC nie je čo kupovať, netreba sa registrovať a aplikácia nezbiera žiadne dáta.",
"abc.parents.privacy": "Prečítajte si zásady ochrany súkromia ABC (v angličtine)",
"abc.safe.ads.t": "Žiadne reklamy",
"abc.safe.ads.d": "Nič vaše dieťa neodvádza od hry.",
"abc.safe.iap.t": "Žiadne nákupy v aplikácii",
"abc.safe.iap.d": "Všetkých deväť hier je súčasťou.",
"abc.safe.data.t": "Žiadny zber dát",
"abc.safe.data.d": "Aplikácia ukladá len niekoľko nastavení, a to iba v zariadení.",
"abc.safe.offline.t": "Funguje offline",
"abc.safe.offline.d": "Na hranie nie je potrebné pripojenie na internet.",
"abc.safe.gate.t": "Časť pre rodičov",
"abc.safe.gate.d": "Nastavenia a odkazy sú za kontrolou pre rodičov.",
"abc.safe.hints.t": "Jemné nápovedy",
"abc.safe.hints.d": "V troch hrách s dvojicami pomáha žiarovka. Vypnúť sa dá v časti Pre rodičov.",
"abc.words.eyebrow": "Ďalší krok: slová",
"abc.words.h2": "Písmená zvládnuté? Čas na slová.",
"abc.words.p": "Flip & Learn: Hra s kartami je z rovnakej rodiny: 21+ kategórií, 9 jazykov a každé slovo zaznie nahlas.",
"abc.words.badge": "Schválené učiteľmi na Google Play",
"abc.words.card": "dog",
"abc.words.cta": "Objavte aplikáciu Flip & Learn: Hra s kartami",
"abc.print.h2": "Pracovné listy na písanie zadarmo",
"abc.print.p": "Vytlačte omaľovánku a obtiahnite slovo ceruzkou. Písmená sa potom dajú precvičiť v hre Písanie písmen.",
"abc.print.cta": "Zobraziť pracovné listy",
"abc.foot.aria": "Päta stránky",
"abc.foot.motto": "Vzdelanie patrí každému dieťaťu.",
"abc.foot.words": "Flip & Learn: Hra s kartami",
"abc.foot.privacy": "Súkromie ABC (po anglicky)",
},
};

module.exports = { A };
