/**
 * abc-strings.js — strings of the Flip & Learn ABC landing page (/abc/, /<loc>/abc/).
 *
 * Same pattern as the T table in index.html and P/PW in privacy-strings.js: one object
 * per locale, keyed by the data-i18n / data-i18n-aria keys used in abc/index.html.
 * build-locales.js merges A[code] over T[code] (which supplies the cookie.* and nav.*
 * keys of the shared chrome) and emits a page for every locale in ABC_LOCALES.
 *
 * Rules for every locale (see build-locales.md):
 *   - "Flip & Learn", "Flip & Learn ABC", "ABC" and "Mo" are never translated.
 *   - The Words app is always called by its Google Play title in the page's language,
 *     verbatim: flipandlearn_flutter android/fastlane/metadata/android/<locale>/title.txt
 *     (en "Flip & Learn: Word Card Game", hu "Flip & Learn: Szókártyajáték",
 *     ro "Flip & Learn: Joc de cuvinte"). Where Play has no localized title, use the
 *     English title. Never inflect, shorten or translate the name; build the sentence
 *     around it. (Rule set by Laci, 2026-10-04.)
 *   - Game names are the app's own on-screen names (ABC repo, lib/l10n/app_<loc>.arb).
 *   - The app teaches the alphabet of English, German, Spanish, French, Romanian,
 *     Hungarian or Italian — never the alphabet of the page's own language unless it
 *     is one of those seven.
 *   - No age claim. Never "completely free". Never the word "memory" or a cognate.
 */
'use strict';

const A = {
en: {
"abc.meta.title": "Flip & Learn ABC — Learn the alphabet by playing",
"abc.meta.ogalt": "The Flip & Learn ABC app icon next to the name Flip & Learn ABC",
"abc.meta.desc": "Nine letter games for small hands: matching, tracing, popping balloons and feeding Mo. Letters and words are spoken in seven languages. Free — no ads, no in-app purchases.",

"abc.nav.aria": "Page sections",
"abc.nav.games": "Games",
"abc.nav.languages": "Languages",
"abc.nav.parents": "For parents",
"abc.nav.words": "Flip & Learn: Word Card Game",
"abc.lang.aria": "Change page language",

"abc.hero.h1": "Learn the alphabet by playing.",
"abc.hero.sub": "Nine little letter games for small hands — matching, tracing, popping balloons and feeding Mo the monster. Letters and words are spoken aloud in English, German, Spanish, French, Romanian, Hungarian and Italian.",
"abc.hero.soon": "Coming soon to the App Store and Google Play",
"abc.badge.apple": "Download Flip & Learn ABC on the App Store",
"abc.badge.play": "Get Flip & Learn ABC on Google Play",
"abc.chip.free": "Free",
"abc.chip.ads": "No ads",
"abc.chip.iap": "No in-app purchases",
"abc.chip.offline": "Works offline",
"abc.chip.data": "No data collected",

"abc.shot.aria": "Screenshots of the app",
"abc.shot.p1.alt": "Flip & Learn ABC Home screen, page 1: Letter Match, Case Match, Word Match, Letter Trace",
"abc.shot.p2.alt": "Flip & Learn ABC Home screen, page 2: Balloon Pop, Hungry Mo, Connect the Dots, Letter Fishing, Sorting Baskets",
"abc.shot.prev": "Previous screen",
"abc.shot.next": "Next screen",
"abc.shot.dot1": "Show page 1",
"abc.shot.dot2": "Show page 2",

"abc.langs.eyebrow": "Letters of the world",
"abc.langs.h2": "Seven alphabets, special letters included.",
"abc.langs.p": "Pick one of seven languages. Its special letters, like Ș, ß, Ñ or Gy, are letters of their own in the games. When no word starts with a letter, Word Match uses a word that contains it.",
"abc.lang.n26": "26 letters",
"abc.lang.n27": "27 letters",
"abc.lang.n30": "30 letters",
"abc.lang.n31": "31 letters",
"abc.lang.n44": "44 letters",
"abc.menus.h3": "Menus in 18 languages",
"abc.menus.p": "English, German, Spanish, French, Italian, Portuguese, Romanian, Hungarian, Turkish, Slovenian, Dutch, Bulgarian, Ukrainian, Russian, Polish, Czech, Slovak and Croatian. With any other device language, the menus are in English.",

"abc.games.eyebrow": "Nine games, one alphabet",
"abc.games.h2": "A new way to meet the letters every day.",
"abc.game.lm.name": "Letter Match",
"abc.game.lm.desc": "Flip the cards and find two of the same letter. Its name is spoken on every match.",
"abc.game.cm.name": "Case Match",
"abc.game.cm.desc": "Pair every capital letter with its small partner.",
"abc.game.wm.name": "Word Match",
"abc.game.wm.word": "dolphin",
"abc.game.wm.desc": "Match a letter to a picture word that starts with it — animals, fruits and more.",
"abc.game.lt.name": "Letter Trace",
"abc.game.lt.desc": "Trace each letter with a finger, stroke by stroke. A moving dot shows the way first.",
"abc.game.bp.name": "Balloon Pop",
"abc.game.bp.desc": "Pop the balloons that carry the letters of the picture word. A new word every game.",
"abc.game.mo.name": "Hungry Mo",
"abc.game.mo.desc": "Mo is hungry. Feed him the pictures that start with his letter — and wait for the burp.",
"abc.game.cd.name": "Connect the Dots",
"abc.game.cd.desc": "Draw from letter to letter in alphabet order. At the last dot the picture fills with color and comes alive.",
"abc.game.lf.name": "Letter Fishing",
"abc.game.lf.desc": "Listen for the letter, then tap the fish that carries it. Five catches make a game.",
"abc.game.sb.name": "Sorting Baskets",
"abc.game.sb.desc": "Drag each picture into the basket of its first letter. Nothing is timed.",

"abc.parents.eyebrow": "For parents",
"abc.parents.h2": "Made by a parent. Safe by design.",
"abc.parents.p1": "Flip & Learn began as an app for my own son. I build every Flip & Learn app myself in Regensburg, Germany, with the same care.",
"abc.parents.p2": "Flip & Learn ABC has nothing to buy, nothing to sign up for, and it collects no data.",
"abc.parents.privacy": "Read the ABC privacy policy",
"abc.safe.ads.t": "No ads",
"abc.safe.ads.d": "Nothing pulls your child out of the game.",
"abc.safe.iap.t": "No in-app purchases",
"abc.safe.iap.d": "All nine games are included.",
"abc.safe.data.t": "No data collected",
"abc.safe.data.d": "The app saves only a few settings, and only on the device.",
"abc.safe.offline.t": "Works offline",
"abc.safe.offline.d": "No internet connection is needed to play.",
"abc.safe.gate.t": "Parents' area",
"abc.safe.gate.d": "Settings and links sit behind a parental gate.",
"abc.safe.hints.t": "Gentle hints",
"abc.safe.hints.d": "A lightbulb helps in the three matching games. Switch it off in the parents' area.",

"abc.words.eyebrow": "Next step: words",
"abc.words.h2": "Letters done? Time for words.",
"abc.words.p": "Flip & Learn: Word Card Game comes from the same family: 21+ categories, 9 languages, and every word spoken out loud.",
"abc.words.badge": "Teacher Approved on Google Play",
"abc.words.card": "dog",
"abc.words.cta": "Discover Flip & Learn: Word Card Game",

"abc.print.h2": "Free tracing worksheets",
"abc.print.p": "Print a coloring page and trace the word with a pencil. Then practice letters in Letter Trace.",
"abc.print.cta": "Get the printables",

"abc.foot.aria": "Footer",
"abc.foot.motto": "Education belongs to every child.",
"abc.foot.words": "Flip & Learn: Word Card Game",
"abc.foot.privacy": "ABC privacy",
},

// Hungarian. Game names, button labels and the phone-mockup texts are taken verbatim
// from the ABC app (lib/l10n/app_hu.arb). Informal address (tegezés), as on /hu/.
hu: {
"abc.meta.title": "Flip & Learn ABC — Tanuld meg az ábécét játszva",
"abc.meta.ogalt": "A Flip & Learn ABC alkalmazás ikonja a Flip & Learn ABC név mellett",
"abc.meta.desc": "Kilenc betűjáték kis kezeknek: párosítás, betűrajzolás, lufipukkasztás és Mo etetése. A betűk és a szavak hét nyelven hangzanak el. Ingyenes — reklámok és alkalmazáson belüli vásárlás nélkül.",

"abc.nav.aria": "Az oldal részei",
"abc.nav.games": "Játékok",
"abc.nav.languages": "Nyelvek",
"abc.nav.parents": "Szülőknek",
"abc.nav.words": "Flip & Learn: Szókártyajáték",
"abc.lang.aria": "Az oldal nyelvének váltása",

"abc.hero.h1": "Tanuld meg az ábécét játszva.",
"abc.hero.sub": "Kilenc kis betűjáték apró kezeknek — párosítás, betűrajzolás, lufipukkasztás és Mo, a szörny etetése. A betűk és a szavak hangosan elhangzanak angolul, németül, spanyolul, franciául, románul, magyarul és olaszul.",
"abc.hero.soon": "Hamarosan az App Store-ban és a Google Playen",
"abc.badge.apple": "A Flip & Learn ABC letöltése az App Store-ból",
"abc.badge.play": "A Flip & Learn ABC letöltése a Google Playről",
"abc.chip.free": "Ingyenes",
"abc.chip.ads": "Nincs reklám",
"abc.chip.iap": "Nincs alkalmazáson belüli vásárlás",
"abc.chip.offline": "Offline működik",
"abc.chip.data": "Nincs adatgyűjtés",

"abc.shot.aria": "Képernyőképek az alkalmazásból",
"abc.shot.p1.alt": "A Flip & Learn ABC kezdőképernyője, 1. oldal: Betűk, Nagy és kis betű, Szavak, Betűk rajzolása",
"abc.shot.p2.alt": "A Flip & Learn ABC kezdőképernyője, 2. oldal: Lufipukkasztás, Éhes Mo, Kösd össze a pontokat, Betűhorgászat, Válogató kosarak",
"abc.shot.prev": "Előző képernyő",
"abc.shot.next": "Következő képernyő",
"abc.shot.dot1": "1. oldal megjelenítése",
"abc.shot.dot2": "2. oldal megjelenítése",

"abc.langs.eyebrow": "A világ betűi",
"abc.langs.h2": "Hét ábécé, a különleges betűkkel együtt.",
"abc.langs.p": "Válassz a hét nyelv közül. A különleges betűk — például Ș, ß, Ñ vagy Gy — a játékokban önálló betűk. Ha egy betűvel nem kezdődik szó, a Szavak játék olyan szót mutat, amelyben a betű szerepel.",
"abc.lang.n26": "26 betű",
"abc.lang.n27": "27 betű",
"abc.lang.n30": "30 betű",
"abc.lang.n31": "31 betű",
"abc.lang.n44": "44 betű",
"abc.menus.h3": "Menük 18 nyelven",
"abc.menus.p": "Angol, német, spanyol, francia, olasz, portugál, román, magyar, török, szlovén, holland, bolgár, ukrán, orosz, lengyel, cseh, szlovák és horvát. Ha a készülék nyelve más, a menük angolul jelennek meg.",

"abc.games.eyebrow": "Kilenc játék, egy ábécé",
"abc.games.h2": "Minden nap új találkozás a betűkkel.",
"abc.game.lm.name": "Betűk",
"abc.game.lm.desc": "Fordítsd fel a kártyákat, és keresd meg a két azonos betűt. Minden találatnál elhangzik a betű neve.",
"abc.game.cm.name": "Nagy és kis betű",
"abc.game.cm.desc": "Párosíts minden nagybetűt a kisbetűs párjával.",
"abc.game.wm.name": "Szavak",
"abc.game.wm.word": "delfin",
"abc.game.wm.desc": "Párosíts egy betűt egy képes szóval, amely azzal a betűvel kezdődik — állatok, gyümölcsök és még sok más.",
"abc.game.lt.name": "Betűk rajzolása",
"abc.game.lt.desc": "Rajzold meg a betűket az ujjaddal, vonásról vonásra. Előbb egy mozgó pont mutatja az utat.",
"abc.game.bp.name": "Lufipukkasztás",
"abc.game.bp.desc": "Pukkaszd ki azokat a lufikat, amelyeken a képhez tartozó szó betűi vannak. Minden játékban új szó.",
"abc.game.mo.name": "Éhes Mo",
"abc.game.mo.desc": "Mo éhes. Etesd meg azokkal a képekkel, amelyek az ő betűjével kezdődnek — és várd meg a böfögést.",
"abc.game.cd.name": "Kösd össze a pontokat",
"abc.game.cd.desc": "Húzz vonalat betűtől betűig, ábécésorrendben. Az utolsó pontnál a kép kiszíneződik és megelevenedik.",
"abc.game.lf.name": "Betűhorgászat",
"abc.game.lf.desc": "Hallgasd meg a betűt, majd koppints arra a halra, amelyiken rajta van. Öt fogás egy játék.",
"abc.game.sb.name": "Válogató kosarak",
"abc.game.sb.desc": "Húzd minden képet a kezdőbetűjének kosarába. Nincs időmérés.",

"abc.parents.eyebrow": "Szülőknek",
"abc.parents.h2": "Egy szülő készítette. Biztonságosra tervezve.",
"abc.parents.p1": "A Flip & Learn a saját fiamnak készült alkalmazásként indult. Minden Flip & Learn alkalmazást magam készítek a németországi Regensburgban, ugyanazzal a gondossággal.",
"abc.parents.p2": "A Flip & Learn ABC-ben nincs mit megvenni, nem kell regisztrálni, és nem gyűjt adatokat.",
"abc.parents.privacy": "Olvasd el az ABC adatvédelmi irányelveit (angol nyelven)",
"abc.safe.ads.t": "Nincs reklám",
"abc.safe.ads.d": "Semmi sem zökkenti ki a gyermekedet a játékból.",
"abc.safe.iap.t": "Nincs alkalmazáson belüli vásárlás",
"abc.safe.iap.d": "Mind a kilenc játék benne van.",
"abc.safe.data.t": "Nincs adatgyűjtés",
"abc.safe.data.d": "Az alkalmazás csak néhány beállítást ment el, és csak a készüléken.",
"abc.safe.offline.t": "Offline működik",
"abc.safe.offline.d": "A játékhoz nem kell internetkapcsolat.",
"abc.safe.gate.t": "Szülői rész",
"abc.safe.gate.d": "A beállítások és a hivatkozások szülői ellenőrzés mögött vannak.",
"abc.safe.hints.t": "Segítség, ha kell",
"abc.safe.hints.d": "A három párosító játékban egy villanykörte segít. A Szülőknek részben kikapcsolható.",

"abc.words.eyebrow": "Következő lépés: szavak",
"abc.words.h2": "Megvannak a betűk? Jöhetnek a szavak.",
"abc.words.p": "A Flip & Learn: Szókártyajáték ugyanebből a családból való: 21+ kategória, 9 nyelv, és minden szót hangosan kimond.",
"abc.words.badge": "Tanárok által jóváhagyva a Google Playen",
"abc.words.card": "kutya",
"abc.words.cta": "Irány a Flip & Learn: Szókártyajáték",

"abc.print.h2": "Ingyenes betűrajzoló feladatlapok",
"abc.print.p": "Nyomtass ki egy színezőt, és rajzold át a szót ceruzával. Utána gyakorold a betűket a Betűk rajzolása játékban.",
"abc.print.cta": "Nyomtatható feladatlapok",

"abc.foot.aria": "Lábléc",
"abc.foot.motto": "Az oktatás minden gyermeket megillet.",
"abc.foot.words": "Flip & Learn: Szókártyajáték",
"abc.foot.privacy": "ABC adatvédelem (angolul)",
},

// Romanian. Game names, button labels and the phone-mockup texts are taken verbatim
// from the ABC app (lib/l10n/app_ro.arb). Informal address (tu), as on /ro/.
// Comma-below Ș ș Ț ț only — never the cedilla forms.
ro: {
"abc.meta.title": "Flip & Learn ABC — Învață alfabetul prin joacă",
"abc.meta.ogalt": "Pictograma aplicației Flip & Learn ABC lângă numele Flip & Learn ABC",
"abc.meta.desc": "Nouă jocuri cu litere pentru mâini mici: potrivire, trasare, spart baloane și hrănirea lui Mo. Literele și cuvintele sunt rostite în șapte limbi. Gratuit — fără reclame, fără achiziții în aplicație.",

"abc.nav.aria": "Secțiunile paginii",
"abc.nav.games": "Jocuri",
"abc.nav.languages": "Limbi",
"abc.nav.parents": "Pentru părinți",
"abc.nav.words": "Flip & Learn: Joc de cuvinte",
"abc.lang.aria": "Schimbă limba paginii",

"abc.hero.h1": "Învață alfabetul prin joacă.",
"abc.hero.sub": "Nouă jocuri cu litere pentru mâini mici — potrivire, trasare, spart baloane și hrănirea lui Mo, monstrul. Literele și cuvintele sunt rostite cu voce tare în engleză, germană, spaniolă, franceză, română, maghiară și italiană.",
"abc.hero.soon": "În curând în App Store și pe Google Play",
"abc.badge.apple": "Descarcă Flip & Learn ABC din App Store",
"abc.badge.play": "Descarcă Flip & Learn ABC de pe Google Play",
"abc.chip.free": "Gratuit",
"abc.chip.ads": "Fără reclame",
"abc.chip.iap": "Fără achiziții în aplicație",
"abc.chip.offline": "Funcționează offline",
"abc.chip.data": "Fără colectare de date",

"abc.shot.aria": "Capturi de ecran din aplicație",
"abc.shot.p1.alt": "Ecranul principal Flip & Learn ABC, pagina 1: Litere, Literă mare și mică, Cuvinte, Trasează literele",
"abc.shot.p2.alt": "Ecranul principal Flip & Learn ABC, pagina 2: Sparge baloanele, Mo cel flămând, Unește punctele, Pescuit de litere, Coșuri de sortat",
"abc.shot.prev": "Ecranul anterior",
"abc.shot.next": "Ecranul următor",
"abc.shot.dot1": "Arată pagina 1",
"abc.shot.dot2": "Arată pagina 2",

"abc.langs.eyebrow": "Literele lumii",
"abc.langs.h2": "Șapte alfabete, cu tot cu literele speciale.",
"abc.langs.p": "Alege una dintre cele șapte limbi. Literele ei speciale, precum Ș, ß, Ñ sau Gy, sunt litere de sine stătătoare în jocuri. Când niciun cuvânt nu începe cu o literă, jocul Cuvinte folosește un cuvânt care o conține.",
"abc.lang.n26": "26 de litere",
"abc.lang.n27": "27 de litere",
"abc.lang.n30": "30 de litere",
"abc.lang.n31": "31 de litere",
"abc.lang.n44": "44 de litere",
"abc.menus.h3": "Meniuri în 18 limbi",
"abc.menus.p": "Engleză, germană, spaniolă, franceză, italiană, portugheză, română, maghiară, turcă, slovenă, neerlandeză, bulgară, ucraineană, rusă, poloneză, cehă, slovacă și croată. Pentru orice altă limbă a dispozitivului, meniurile sunt în engleză.",

"abc.games.eyebrow": "Nouă jocuri, un alfabet",
"abc.games.h2": "În fiecare zi, un nou fel de a întâlni literele.",
"abc.game.lm.name": "Litere",
"abc.game.lm.desc": "Întoarce cărțile și găsește două cu aceeași literă. La fiecare pereche, numele literei este rostit.",
"abc.game.cm.name": "Literă mare și mică",
"abc.game.cm.desc": "Potrivește fiecare literă mare cu perechea ei mică.",
"abc.game.wm.name": "Cuvinte",
"abc.game.wm.word": "delfin",
"abc.game.wm.desc": "Potrivește o literă cu un cuvânt ilustrat care începe cu ea — animale, fructe și multe altele.",
"abc.game.lt.name": "Trasează literele",
"abc.game.lt.desc": "Trasează fiecare literă cu degetul, linie cu linie. Mai întâi, un punct în mișcare arată drumul.",
"abc.game.bp.name": "Sparge baloanele",
"abc.game.bp.desc": "Sparge baloanele care poartă literele cuvântului din imagine. La fiecare joc, un cuvânt nou.",
"abc.game.mo.name": "Mo cel flămând",
"abc.game.mo.desc": "Lui Mo îi este foame. Dă-i imaginile care încep cu litera lui — și așteaptă râgâitul.",
"abc.game.cd.name": "Unește punctele",
"abc.game.cd.desc": "Trasează de la literă la literă, în ordine alfabetică. La ultimul punct, imaginea se umple de culoare și prinde viață.",
"abc.game.lf.name": "Pescuit de litere",
"abc.game.lf.desc": "Ascultă litera, apoi atinge peștele care o poartă. Cinci capturi fac un joc.",
"abc.game.sb.name": "Coșuri de sortat",
"abc.game.sb.desc": "Trage fiecare imagine în coșul primei ei litere. Nimic nu este cronometrat.",

"abc.parents.eyebrow": "Pentru părinți",
"abc.parents.h2": "Creat de un părinte. Sigur prin concepție.",
"abc.parents.p1": "Flip & Learn a început ca o aplicație pentru fiul meu. Fac eu însumi fiecare aplicație Flip & Learn, în Regensburg, Germania, cu aceeași grijă.",
"abc.parents.p2": "În Flip & Learn ABC nu e nimic de cumpărat, nu trebuie creat niciun cont și nu se colectează date.",
"abc.parents.privacy": "Citește politica de confidențialitate ABC (în limba engleză)",
"abc.safe.ads.t": "Fără reclame",
"abc.safe.ads.d": "Nimic nu îți scoate copilul din joc.",
"abc.safe.iap.t": "Fără achiziții în aplicație",
"abc.safe.iap.d": "Toate cele nouă jocuri sunt incluse.",
"abc.safe.data.t": "Fără colectare de date",
"abc.safe.data.d": "Aplicația salvează doar câteva setări, și numai pe dispozitiv.",
"abc.safe.offline.t": "Funcționează offline",
"abc.safe.offline.d": "Nu este nevoie de internet pentru a juca.",
"abc.safe.gate.t": "Zona pentru părinți",
"abc.safe.gate.d": "Setările și linkurile se află în spatele controlului parental.",
"abc.safe.hints.t": "Indicii blânde",
"abc.safe.hints.d": "Un bec ajută în cele trei jocuri de potrivire. Se poate dezactiva în zona Pentru părinți.",

"abc.words.eyebrow": "Pasul următor: cuvinte",
"abc.words.h2": "Gata cu literele? E timpul pentru cuvinte.",
"abc.words.p": "Flip & Learn: Joc de cuvinte vine din aceeași familie: 21+ categorii, 9 limbi și fiecare cuvânt rostit cu voce tare.",
"abc.words.badge": "Aprobat de profesori pe Google Play",
"abc.words.card": "câine",
"abc.words.cta": "Descoperă Flip & Learn: Joc de cuvinte",

"abc.print.h2": "Fișe de colorat gratuite cu exerciții de scriere",
"abc.print.p": "Printează o fișă de colorat și trasează cuvântul cu creionul. Apoi exersează literele în jocul Trasează literele.",
"abc.print.cta": "Vezi fișele de colorat",

"abc.foot.aria": "Subsol",
"abc.foot.motto": "Educația aparține fiecărui copil.",
"abc.foot.words": "Flip & Learn: Joc de cuvinte",
"abc.foot.privacy": "Confidențialitate ABC (în engleză)",
},
};

module.exports = { A };
