/**
 * family-strings.js — the "More from Flip & Learn" card and the Flip & Learn ABC nav/footer
 * links on the 31 Words homepages. Rendered ONLY when ABC_LAUNCHED is true in
 * build-locales.js; with the flag false none of this reaches the output.
 *
 * Same rules as abc-strings.js: "Flip & Learn", "Flip & Learn ABC" and "ABC" are never
 * translated or inflected; no age claim; never "completely free"; never "memory".
 * family.text is the ABC page's tagline (abc.meta.title after the dash), so the card
 * says the same thing as the page it links to; family.facts repeats three ABC chips.
 * hu/ro: reviewed by Laci.
 */
'use strict';

const F = {
en: {
"family.eyebrow": "More from Flip & Learn",
"family.new": "New",
"family.text": "Learn the alphabet by playing, in seven languages.",
"family.facts": "Free · No ads · No in-app purchases",
"family.cta": "Discover Flip & Learn ABC",
"family.nav": "Flip & Learn ABC",
"family.foot": "Flip & Learn ABC",
},
de: {
"family.eyebrow": "Mehr von Flip & Learn",
"family.new": "Neu",
"family.text": "Das Alphabet spielend lernen, in sieben Sprachen.",
"family.facts": "Kostenlos · Keine Werbung · Keine In-App-Käufe",
"family.cta": "Flip & Learn ABC entdecken",
"family.nav": "Flip & Learn ABC",
"family.foot": "Flip & Learn ABC",
},
fr: {
"family.eyebrow": "Aussi chez Flip & Learn",
"family.new": "Nouveau",
"family.text": "Apprendre l'alphabet en jouant, en sept langues.",
"family.facts": "Gratuit · Sans publicité · Sans achats intégrés",
"family.cta": "Découvrir Flip & Learn ABC",
"family.nav": "Flip & Learn ABC",
"family.foot": "Flip & Learn ABC",
},
es: {
"family.eyebrow": "Más de Flip & Learn",
"family.new": "Nuevo",
"family.text": "Aprende el abecedario jugando, en siete idiomas.",
"family.facts": "Gratis · Sin publicidad · Sin compras en la app",
"family.cta": "Descubrir Flip & Learn ABC",
"family.nav": "Flip & Learn ABC",
"family.foot": "Flip & Learn ABC",
},
it: {
"family.eyebrow": "Anche da Flip & Learn",
"family.new": "Novità",
"family.text": "Impara l'alfabeto giocando, in sette lingue.",
"family.facts": "Gratis · Senza pubblicità · Senza acquisti in-app",
"family.cta": "Scopri Flip & Learn ABC",
"family.nav": "Flip & Learn ABC",
"family.foot": "Flip & Learn ABC",
},
pt: {
"family.eyebrow": "Mais de Flip & Learn",
"family.new": "Novo",
"family.text": "Aprender o alfabeto a brincar, em sete línguas.",
"family.facts": "Grátis · Sem publicidade · Sem compras na app",
"family.cta": "Descobrir Flip & Learn ABC",
"family.nav": "Flip & Learn ABC",
"family.foot": "Flip & Learn ABC",
},
ro: {
"family.eyebrow": "Mai multe de la Flip & Learn",
"family.new": "Nou",
"family.text": "Învață alfabetul prin joacă, în șapte limbi.",
"family.facts": "Gratuit · Fără reclame · Fără achiziții în aplicație",
"family.cta": "Descoperă Flip & Learn ABC",
"family.nav": "Flip & Learn ABC",
"family.foot": "Flip & Learn ABC",
},
hu: {
"family.eyebrow": "Még több Flip & Learn",
"family.new": "Új",
"family.text": "Tanuld meg az ábécét játszva, hét nyelven.",
"family.facts": "Ingyenes · Nincs reklám · Nincs alkalmazáson belüli vásárlás",
"family.cta": "Ismerd meg: Flip & Learn ABC",
"family.nav": "Flip & Learn ABC",
"family.foot": "Flip & Learn ABC",
},
pl: {
"family.eyebrow": "Więcej od Flip & Learn",
"family.new": "Nowość",
"family.text": "Nauka alfabetu przez zabawę, w siedmiu językach.",
"family.facts": "Bezpłatnie · Bez reklam · Bez zakupów w aplikacji",
"family.cta": "Poznaj Flip & Learn ABC",
"family.nav": "Flip & Learn ABC",
"family.foot": "Flip & Learn ABC",
},
nl: {
"family.eyebrow": "Meer van Flip & Learn",
"family.new": "Nieuw",
"family.text": "Spelend het alfabet leren, in zeven talen.",
"family.facts": "Gratis · Geen reclame · Geen in-app-aankopen",
"family.cta": "Ontdek Flip & Learn ABC",
"family.nav": "Flip & Learn ABC",
"family.foot": "Flip & Learn ABC",
},
ru: {
"family.eyebrow": "Ещё от Flip & Learn",
"family.new": "Новинка",
"family.text": "Латинский алфавит в игре, на семи языках.",
"family.facts": "Бесплатно · Без рекламы · Без покупок в приложении",
"family.cta": "Подробнее: Flip & Learn ABC",
"family.nav": "Flip & Learn ABC",
"family.foot": "Flip & Learn ABC",
},
uk: {
"family.eyebrow": "Ще від Flip & Learn",
"family.new": "Новинка",
"family.text": "Латинська абетка у грі, сімома мовами.",
"family.facts": "Безкоштовно · Без реклами · Без покупок у застосунку",
"family.cta": "Детальніше: Flip & Learn ABC",
"family.nav": "Flip & Learn ABC",
"family.foot": "Flip & Learn ABC",
},
bg: {
"family.eyebrow": "Още от Flip & Learn",
"family.new": "Ново",
"family.text": "Латинската азбука с игра, на седем езика.",
"family.facts": "Безплатно · Без реклами · Без покупки в приложението",
"family.cta": "Вижте Flip & Learn ABC",
"family.nav": "Flip & Learn ABC",
"family.foot": "Flip & Learn ABC",
},
tr: {
"family.eyebrow": "Flip & Learn ailesi",
"family.new": "Yeni",
"family.text": "Oynayarak alfabe öğren, yedi dilde.",
"family.facts": "Ücretsiz · Reklam yok · Uygulama içi satın alma yok",
"family.cta": "Keşfet: Flip & Learn ABC",
"family.nav": "Flip & Learn ABC",
"family.foot": "Flip & Learn ABC",
},
cs: {
"family.eyebrow": "Další od Flip & Learn",
"family.new": "Novinka",
"family.text": "Abeceda hrou, v sedmi jazycích.",
"family.facts": "Zdarma · Žádné reklamy · Žádné nákupy v aplikaci",
"family.cta": "Objevte Flip & Learn ABC",
"family.nav": "Flip & Learn ABC",
"family.foot": "Flip & Learn ABC",
},
sk: {
"family.eyebrow": "Ďalšie od Flip & Learn",
"family.new": "Novinka",
"family.text": "Abeceda hrou, v siedmich jazykoch.",
"family.facts": "Zadarmo · Žiadne reklamy · Žiadne nákupy v aplikácii",
"family.cta": "Objavte Flip & Learn ABC",
"family.nav": "Flip & Learn ABC",
"family.foot": "Flip & Learn ABC",
},
hr: {
"family.eyebrow": "Još od Flip & Learn",
"family.new": "Novo",
"family.text": "Abeceda kroz igru, na sedam jezika.",
"family.facts": "Besplatno · Bez reklama · Bez kupnji u aplikaciji",
"family.cta": "Otkrijte Flip & Learn ABC",
"family.nav": "Flip & Learn ABC",
"family.foot": "Flip & Learn ABC",
},
sl: {
"family.eyebrow": "Še od Flip & Learn",
"family.new": "Novo",
"family.text": "Abeceda skozi igro, v sedmih jezikih.",
"family.facts": "Brezplačno · Brez oglasov · Brez nakupov v aplikaciji",
"family.cta": "Odkrijte Flip & Learn ABC",
"family.nav": "Flip & Learn ABC",
"family.foot": "Flip & Learn ABC",
},
el: {
"family.eyebrow": "Περισσότερα από το Flip & Learn",
"family.new": "Νέο",
"family.text": "Το λατινικό αλφάβητο παίζοντας, σε επτά γλώσσες.",
"family.facts": "Δωρεάν · Χωρίς διαφημίσεις · Χωρίς αγορές εντός εφαρμογής",
"family.cta": "Δείτε το Flip & Learn ABC",
"family.nav": "Flip & Learn ABC",
"family.foot": "Flip & Learn ABC",
},
sv: {
"family.eyebrow": "Mer från Flip & Learn",
"family.new": "Nyhet",
"family.text": "Lär dig alfabetet genom lek, på sju språk.",
"family.facts": "Gratis · Ingen reklam · Inga köp i appen",
"family.cta": "Upptäck Flip & Learn ABC",
"family.nav": "Flip & Learn ABC",
"family.foot": "Flip & Learn ABC",
},
da: {
"family.eyebrow": "Mere fra Flip & Learn",
"family.new": "Nyhed",
"family.text": "Lær alfabetet gennem leg, på syv sprog.",
"family.facts": "Gratis · Ingen reklamer · Ingen køb i appen",
"family.cta": "Opdag Flip & Learn ABC",
"family.nav": "Flip & Learn ABC",
"family.foot": "Flip & Learn ABC",
},
no: {
"family.eyebrow": "Mer fra Flip & Learn",
"family.new": "Nyhet",
"family.text": "Lær alfabetet gjennom lek, på sju språk.",
"family.facts": "Gratis · Ingen reklame · Ingen kjøp i appen",
"family.cta": "Oppdag Flip & Learn ABC",
"family.nav": "Flip & Learn ABC",
"family.foot": "Flip & Learn ABC",
},
fi: {
"family.eyebrow": "Lisää Flip & Learn -perheestä",
"family.new": "Uutta",
"family.text": "Opi aakkoset leikkien, seitsemällä kielellä.",
"family.facts": "Ilmainen · Ei mainoksia · Ei sovelluksen sisäisiä ostoksia",
"family.cta": "Tutustu: Flip & Learn ABC",
"family.nav": "Flip & Learn ABC",
"family.foot": "Flip & Learn ABC",
},
lt: {
"family.eyebrow": "Daugiau iš Flip & Learn",
"family.new": "Naujiena",
"family.text": "Mokykis abėcėlės žaisdamas, septyniomis kalbomis.",
"family.facts": "Nemokamai · Be reklamų · Be pirkimų programėlėje",
"family.cta": "Atrask Flip & Learn ABC",
"family.nav": "Flip & Learn ABC",
"family.foot": "Flip & Learn ABC",
},
lv: {
"family.eyebrow": "Vēl no Flip & Learn",
"family.new": "Jaunums",
"family.text": "Apgūsti alfabētu rotaļājoties, septiņās valodās.",
"family.facts": "Bez maksas · Bez reklāmām · Bez pirkumiem lietotnē",
"family.cta": "Iepazīsti Flip & Learn ABC",
"family.nav": "Flip & Learn ABC",
"family.foot": "Flip & Learn ABC",
},
et: {
"family.eyebrow": "Veel sarjast Flip & Learn",
"family.new": "Uus",
"family.text": "Õpi tähestikku mängides, seitsmes keeles.",
"family.facts": "Tasuta · Reklaamideta · Rakendusesiseste ostudeta",
"family.cta": "Tutvu: Flip & Learn ABC",
"family.nav": "Flip & Learn ABC",
"family.foot": "Flip & Learn ABC",
},
sq: {
"family.eyebrow": "Më shumë nga Flip & Learn",
"family.new": "E re",
"family.text": "Mëso alfabetin duke luajtur, në shtatë gjuhë.",
"family.facts": "Falas · Pa reklama · Pa blerje brenda aplikacionit",
"family.cta": "Zbulo Flip & Learn ABC",
"family.nav": "Flip & Learn ABC",
"family.foot": "Flip & Learn ABC",
},
sr: {
"family.eyebrow": "Још од Flip & Learn",
"family.new": "Ново",
"family.text": "Латиничка абецеда кроз игру, на седам језика.",
"family.facts": "Бесплатно · Без реклама · Без куповина у апликацији",
"family.cta": "Упознајте Flip & Learn ABC",
"family.nav": "Flip & Learn ABC",
"family.foot": "Flip & Learn ABC",
},
ja: {
"family.eyebrow": "Flip & Learn のアプリ",
"family.new": "新登場",
"family.text": "7つの言語のアルファベットを、遊びながら。",
"family.facts": "無料 · 広告なし · アプリ内課金なし",
"family.cta": "Flip & Learn ABC を見る",
"family.nav": "Flip & Learn ABC",
"family.foot": "Flip & Learn ABC",
},
ko: {
"family.eyebrow": "Flip & Learn의 다른 앱",
"family.new": "새 앱",
"family.text": "놀면서 배우는 7개 언어의 알파벳.",
"family.facts": "무료 · 광고 없음 · 인앱 구매 없음",
"family.cta": "Flip & Learn ABC 알아보기",
"family.nav": "Flip & Learn ABC",
"family.foot": "Flip & Learn ABC",
},
ar: {
"family.eyebrow": "المزيد من Flip & Learn",
"family.new": "جديد",
"family.text": "الحروف اللاتينية باللعب، بسبع لغات.",
"family.facts": "مجاني · بلا إعلانات · بلا مشتريات داخل التطبيق",
"family.cta": "اكتشف Flip & Learn ABC",
"family.nav": "Flip & Learn ABC",
"family.foot": "Flip & Learn ABC",
},
};

module.exports = { F };
